#ifndef GPIO_REGISTERS_H
#define GPIO_REGISTERS_H
/**
 * @copyright
 * @file gpio.h
 * @author Andrea Gianarda
 * @date 22nd of February 2021
 * @brief General purpose I/O registers
*/

#include <stdint.h>

#include "global/peripherals.h"

/**
 *  @defgroup RegisterGroup Register global macros, structure and functions
 *  @brief Registers global macros, structure and functions
 *  @{
 */

/**
 *  @ingroup RegisterGroup
 *  @defgroup GPIO General purpose I/O
 *  @brief GPIO General purpose I/O macros and structures
 *  @{
 */

typedef struct {
	RW uint32_t MODE;        /*!< Mode register                    (Offset 0x0)         */
	RW uint32_t OTYPE;       /*!< Output type register             (Offset 0x4)         */
	RW uint32_t OSPEED;      /*!< Output speed register            (Offset 0x8)         */
	RW uint32_t PUPD;        /*!< Pull up/pull down register       (Offset 0xC)         */
	RO uint32_t IDATA;       /*!< Input data register              (Offset 0x10)        */
	RW uint32_t ODATA;       /*!< Output data register             (Offset 0x14)        */
	WO uint32_t BSR;         /*!< Bit set/reset register           (Offset 0x18)        */
	RW uint32_t PORTCFGLOCK; /*!< Port configuration lock register (Offset 0x1C)        */
	RW uint32_t ALTFUNC[2];  /*!< Alternate function register      (Offset 0x20 - 0x24) */
} gpio_regs;

/*!< GPIO registers */
/*!< Mode register */
#define GPIO_MODE_PIN15_OFFSET (30U)
#define GPIO_MODE_PIN15_MASK   (0x3UL << REGISTER_FIELD_OFFSET(GPIO, MODE, PIN15))  /*!< Mask  0xC0000000 */

#define GPIO_MODE_PIN14_OFFSET (28U)
#define GPIO_MODE_PIN14_MASK   (0x3UL << REGISTER_FIELD_OFFSET(GPIO, MODE, PIN14))  /*!< Mask  0x30000000 */

#define GPIO_MODE_PIN13_OFFSET (26U)
#define GPIO_MODE_PIN13_MASK   (0x3UL << REGISTER_FIELD_OFFSET(GPIO, MODE, PIN13))  /*!< Mask  0x0C000000 */

#define GPIO_MODE_PIN12_OFFSET (24U)
#define GPIO_MODE_PIN12_MASK   (0x3UL << REGISTER_FIELD_OFFSET(GPIO, MODE, PIN12))  /*!< Mask  0x03000000 */

#define GPIO_MODE_PIN11_OFFSET (22U)
#define GPIO_MODE_PIN11_MASK   (0x3UL << REGISTER_FIELD_OFFSET(GPIO, MODE, PIN11))  /*!< Mask  0x00C00000 */

#define GPIO_MODE_PIN10_OFFSET (20U)
#define GPIO_MODE_PIN10_MASK   (0x3UL << REGISTER_FIELD_OFFSET(GPIO, MODE, PIN10))  /*!< Mask  0x00300000 */

#define GPIO_MODE_PIN9_OFFSET  (18U)
#define GPIO_MODE_PIN9_MASK    (0x3UL << REGISTER_FIELD_OFFSET(GPIO, MODE, PIN9))   /*!< Mask  0x000C0000 */

#define GPIO_MODE_PIN8_OFFSET  (16U)
#define GPIO_MODE_PIN8_MASK    (0x3UL << REGISTER_FIELD_OFFSET(GPIO, MODE, PIN8))   /*!< Mask  0x00030000 */

#define GPIO_MODE_PIN7_OFFSET  (14U)
#define GPIO_MODE_PIN7_MASK    (0x3UL << REGISTER_FIELD_OFFSET(GPIO, MODE, PIN7))   /*!< Mask  0x0000C000 */

#define GPIO_MODE_PIN6_OFFSET  (12U)
#define GPIO_MODE_PIN6_MASK    (0x3UL << REGISTER_FIELD_OFFSET(GPIO, MODE, PIN6))   /*!< Mask  0x00003000 */

#define GPIO_MODE_PIN5_OFFSET  (10U)
#define GPIO_MODE_PIN5_MASK    (0x3UL << REGISTER_FIELD_OFFSET(GPIO, MODE, PIN5))   /*!< Mask  0x00000C00 */

#define GPIO_MODE_PIN4_OFFSET  (8U)
#define GPIO_MODE_PIN4_MASK    (0x3UL << REGISTER_FIELD_OFFSET(GPIO, MODE, PIN4))   /*!< Mask  0x00000300 */

#define GPIO_MODE_PIN3_OFFSET  (6U)
#define GPIO_MODE_PIN3_MASK    (0x3UL << REGISTER_FIELD_OFFSET(GPIO, MODE, PIN3))   /*!< Mask  0x000000C0 */

#define GPIO_MODE_PIN2_OFFSET  (4U)
#define GPIO_MODE_PIN2_MASK    (0x3UL << REGISTER_FIELD_OFFSET(GPIO, MODE, PIN2))   /*!< Mask  0x00000030 */

#define GPIO_MODE_PIN1_OFFSET  (2U)
#define GPIO_MODE_PIN1_MASK    (0x3UL << REGISTER_FIELD_OFFSET(GPIO, MODE, PIN1))   /*!< Mask  0x0000000C */

#define GPIO_MODE_PIN0_OFFSET  (0U)
#define GPIO_MODE_PIN0_MASK    (0x3UL << REGISTER_FIELD_OFFSET(GPIO, MODE, PIN0))   /*!< Mask  0x00000003 */

// Value of the GPIO mode for each GPIO pin
#define GPIO_MODE_INPUT    (0x0UL)  /*!< Value 0x00000000 */
#define GPIO_MODE_OUTPUT   (0x1UL)  /*!< Value 0x00000001 */
#define GPIO_MODE_ALTFUNC  (0x2UL)  /*!< Value 0x00000002 */
#define GPIO_MODE_ANALOG   (0x3UL)  /*!< Value 0x00000003 */

/*!< Output type register */
#define GPIO_OTYPE_OTYPE15_OFFSET (15U)
#define GPIO_OTYPE_OTYPE15_MASK   (0x1UL << REGISTER_FIELD_OFFSET(GPIO, OTYPE, OTYPE15))  /*!< Mask  0x00008000 */

#define GPIO_OTYPE_OTYPE14_OFFSET (14U)
#define GPIO_OTYPE_OTYPE14_MASK   (0x1UL << REGISTER_FIELD_OFFSET(GPIO, OTYPE, OTYPE14))  /*!< Mask  0x00004000 */

#define GPIO_OTYPE_OTYPE13_OFFSET (13U)
#define GPIO_OTYPE_OTYPE13_MASK   (0x1UL << REGISTER_FIELD_OFFSET(GPIO, OTYPE, OTYPE13))  /*!< Mask  0x00002000 */

#define GPIO_OTYPE_OTYPE12_OFFSET (12U)
#define GPIO_OTYPE_OTYPE12_MASK   (0x1UL << REGISTER_FIELD_OFFSET(GPIO, OTYPE, OTYPE12))  /*!< Mask  0x00001000 */

#define GPIO_OTYPE_OTYPE11_OFFSET (11U)
#define GPIO_OTYPE_OTYPE11_MASK   (0x1UL << REGISTER_FIELD_OFFSET(GPIO, OTYPE, OTYPE11))  /*!< Mask  0x00000800 */

#define GPIO_OTYPE_OTYPE10_OFFSET (10U)
#define GPIO_OTYPE_OTYPE10_MASK   (0x1UL << REGISTER_FIELD_OFFSET(GPIO, OTYPE, OTYPE10))  /*!< Mask  0x00000400 */

#define GPIO_OTYPE_OTYPE9_OFFSET  (9U)
#define GPIO_OTYPE_OTYPE9_MASK    (0x1UL << REGISTER_FIELD_OFFSET(GPIO, OTYPE, OTYPE9))   /*!< Mask  0x00000200 */

#define GPIO_OTYPE_OTYPE8_OFFSET  (8U)
#define GPIO_OTYPE_OTYPE8_MASK    (0x1UL << REGISTER_FIELD_OFFSET(GPIO, OTYPE, OTYPE8))   /*!< Mask  0x00000100 */

#define GPIO_OTYPE_OTYPE7_OFFSET  (7U)
#define GPIO_OTYPE_OTYPE7_MASK    (0x1UL << REGISTER_FIELD_OFFSET(GPIO, OTYPE, OTYPE7))   /*!< Mask  0x00000080 */

#define GPIO_OTYPE_OTYPE6_OFFSET  (6U)
#define GPIO_OTYPE_OTYPE6_MASK    (0x1UL << REGISTER_FIELD_OFFSET(GPIO, OTYPE, OTYPE6))   /*!< Mask  0x00000040 */

#define GPIO_OTYPE_OTYPE5_OFFSET  (5U)
#define GPIO_OTYPE_OTYPE5_MASK    (0x1UL << REGISTER_FIELD_OFFSET(GPIO, OTYPE, OTYPE5))   /*!< Mask  0x00000020 */

#define GPIO_OTYPE_OTYPE4_OFFSET  (4U)
#define GPIO_OTYPE_OTYPE4_MASK    (0x1UL << REGISTER_FIELD_OFFSET(GPIO, OTYPE, OTYPE4))   /*!< Mask  0x00000010 */

#define GPIO_OTYPE_OTYPE3_OFFSET  (3U)
#define GPIO_OTYPE_OTYPE3_MASK    (0x1UL << REGISTER_FIELD_OFFSET(GPIO, OTYPE, OTYPE3))   /*!< Mask  0x00000008 */

#define GPIO_OTYPE_OTYPE2_OFFSET  (2U)
#define GPIO_OTYPE_OTYPE2_MASK    (0x1UL << REGISTER_FIELD_OFFSET(GPIO, OTYPE, OTYPE2))   /*!< Mask  0x00000004 */

#define GPIO_OTYPE_OTYPE1_OFFSET  (1U)
#define GPIO_OTYPE_OTYPE1_MASK    (0x1UL << REGISTER_FIELD_OFFSET(GPIO, OTYPE, OTYPE1))   /*!< Mask  0x00000002 */

#define GPIO_OTYPE_OTYPE0_OFFSET  (0U)
#define GPIO_OTYPE_OTYPE0_MASK    (0x1UL << REGISTER_FIELD_OFFSET(GPIO, OTYPE, OTYPE0))   /*!< Mask  0x00000001 */

// Value of output type registers for each GPIO pin
#define GPIO_OTYPE_PUSHPULL   (0x0UL)  /*!< Value 0x00000000 */
#define GPIO_OTYPE_OPENDRAIN  (0x1UL)  /*!< Value 0x00000001 */

/*!< Output speed register */
#define GPIO_OSPEED_PIN15_OFFSET (30U)
#define GPIO_OSPEED_PIN15_MASK   (0x3UL << REGISTER_FIELD_OFFSET(GPIO, OSPEED, PIN15))  /*!< Mask  0xC0000000 */

#define GPIO_OSPEED_PIN14_OFFSET (28U)
#define GPIO_OSPEED_PIN14_MASK   (0x3UL << REGISTER_FIELD_OFFSET(GPIO, OSPEED, PIN14))  /*!< Mask  0x30000000 */

#define GPIO_OSPEED_PIN13_OFFSET (26U)
#define GPIO_OSPEED_PIN13_MASK   (0x3UL << REGISTER_FIELD_OFFSET(GPIO, OSPEED, PIN13))  /*!< Mask  0x0C000000 */

#define GPIO_OSPEED_PIN12_OFFSET (24U)
#define GPIO_OSPEED_PIN12_MASK   (0x3UL << REGISTER_FIELD_OFFSET(GPIO, OSPEED, PIN12))  /*!< Mask  0x03000000 */

#define GPIO_OSPEED_PIN11_OFFSET (22U)
#define GPIO_OSPEED_PIN11_MASK   (0x3UL << REGISTER_FIELD_OFFSET(GPIO, OSPEED, PIN11))  /*!< Mask  0x00C00000 */

#define GPIO_OSPEED_PIN10_OFFSET (20U)
#define GPIO_OSPEED_PIN10_MASK   (0x3UL << REGISTER_FIELD_OFFSET(GPIO, OSPEED, PIN10))  /*!< Mask  0x00300000 */

#define GPIO_OSPEED_PIN9_OFFSET  (18U)
#define GPIO_OSPEED_PIN9_MASK    (0x3UL << REGISTER_FIELD_OFFSET(GPIO, OSPEED, PIN9))   /*!< Mask  0x000C0000 */

#define GPIO_OSPEED_PIN8_OFFSET  (16U)
#define GPIO_OSPEED_PIN8_MASK    (0x3UL << REGISTER_FIELD_OFFSET(GPIO, OSPEED, PIN8))   /*!< Mask  0x00030000 */

#define GPIO_OSPEED_PIN7_OFFSET  (14U)
#define GPIO_OSPEED_PIN7_MASK    (0x3UL << REGISTER_FIELD_OFFSET(GPIO, OSPEED, PIN7))   /*!< Mask  0x0000C000 */

#define GPIO_OSPEED_PIN6_OFFSET  (12U)
#define GPIO_OSPEED_PIN6_MASK    (0x3UL << REGISTER_FIELD_OFFSET(GPIO, OSPEED, PIN6))   /*!< Mask  0x00003000 */

#define GPIO_OSPEED_PIN5_OFFSET  (10U)
#define GPIO_OSPEED_PIN5_MASK    (0x3UL << REGISTER_FIELD_OFFSET(GPIO, OSPEED, PIN5))   /*!< Mask  0x00000C00 */

#define GPIO_OSPEED_PIN4_OFFSET  (8U)
#define GPIO_OSPEED_PIN4_MASK    (0x3UL << REGISTER_FIELD_OFFSET(GPIO, OSPEED, PIN4))   /*!< Mask  0x00000300 */

#define GPIO_OSPEED_PIN3_OFFSET  (6U)
#define GPIO_OSPEED_PIN3_MASK    (0x3UL << REGISTER_FIELD_OFFSET(GPIO, OSPEED, PIN3))   /*!< Mask  0x000000C0 */

#define GPIO_OSPEED_PIN2_OFFSET  (4U)
#define GPIO_OSPEED_PIN2_MASK    (0x3UL << REGISTER_FIELD_OFFSET(GPIO, OSPEED, PIN2))   /*!< Mask  0x00000020 */

#define GPIO_OSPEED_PIN1_OFFSET  (2U)
#define GPIO_OSPEED_PIN1_MASK    (0x3UL << REGISTER_FIELD_OFFSET(GPIO, OSPEED, PIN1))   /*!< Mask  0x0000000C */

#define GPIO_OSPEED_PIN0_OFFSET  (0U)
#define GPIO_OSPEED_PIN0_MASK    (0x3UL << REGISTER_FIELD_OFFSET(GPIO, OSPEED, PIN0))   /*!< Mask  0x00000003 */

// Value of speed registers for each GPIO pin
#define GPIO_SPEED_LOW       (0x0UL)  /*!< Value 0x00000000 */
#define GPIO_SPEED_MEDIUM    (0x1UL)  /*!< Value 0x00000001 */
#define GPIO_SPEED_HIGH      (0x2UL)  /*!< Value 0x00000002 */
#define GPIO_SPEED_VERYHIGH  (0x3UL)  /*!< Value 0x00000003 */

/*!< Pull up/pull down register */
#define GPIO_PUPD_PIN15_OFFSET (30U)
#define GPIO_PUPD_PIN15_MASK   (0x3UL << REGISTER_FIELD_OFFSET(GPIO, PUPD, PIN15))  /*!< Mask  0xC0000000 */

#define GPIO_PUPD_PIN14_OFFSET (28U)
#define GPIO_PUPD_PIN14_MASK   (0x3UL << REGISTER_FIELD_OFFSET(GPIO, PUPD, PIN14))  /*!< Mask  0x30000000 */

#define GPIO_PUPD_PIN13_OFFSET (26U)
#define GPIO_PUPD_PIN13_MASK   (0x3UL << REGISTER_FIELD_OFFSET(GPIO, PUPD, PIN13))  /*!< Mask  0x0C000000 */

#define GPIO_PUPD_PIN12_OFFSET (24U)
#define GPIO_PUPD_PIN12_MASK   (0x3UL << REGISTER_FIELD_OFFSET(GPIO, PUPD, PIN12))  /*!< Mask  0x03000000 */

#define GPIO_PUPD_PIN11_OFFSET (22U)
#define GPIO_PUPD_PIN11_MASK   (0x3UL << REGISTER_FIELD_OFFSET(GPIO, PUPD, PIN11))  /*!< Mask  0x00C00000 */

#define GPIO_PUPD_PIN10_OFFSET (20U)
#define GPIO_PUPD_PIN10_MASK   (0x3UL << REGISTER_FIELD_OFFSET(GPIO, PUPD, PIN10))  /*!< Mask  0x00300000 */

#define GPIO_PUPD_PIN9_OFFSET  (18U)
#define GPIO_PUPD_PIN9_MASK    (0x3UL << REGISTER_FIELD_OFFSET(GPIO, PUPD, PIN9))   /*!< Mask  0x000C0000 */

#define GPIO_PUPD_PIN8_OFFSET  (16U)
#define GPIO_PUPD_PIN8_MASK    (0x3UL << REGISTER_FIELD_OFFSET(GPIO, PUPD, PIN8))   /*!< Mask  0x00030000 */

#define GPIO_PUPD_PIN7_OFFSET  (14U)
#define GPIO_PUPD_PIN7_MASK    (0x3UL << REGISTER_FIELD_OFFSET(GPIO, PUPD, PIN7))   /*!< Mask  0x0000C000 */

#define GPIO_PUPD_PIN6_OFFSET  (12U)
#define GPIO_PUPD_PIN6_MASK    (0x3UL << REGISTER_FIELD_OFFSET(GPIO, PUPD, PIN6))   /*!< Mask  0x00003000 */

#define GPIO_PUPD_PIN5_OFFSET  (10U)
#define GPIO_PUPD_PIN5_MASK    (0x3UL << REGISTER_FIELD_OFFSET(GPIO, PUPD, PIN5))   /*!< Mask  0x00000C00 */

#define GPIO_PUPD_PIN4_OFFSET  (8U)
#define GPIO_PUPD_PIN4_MASK    (0x3UL << REGISTER_FIELD_OFFSET(GPIO, PUPD, PIN4))   /*!< Mask  0x00000300 */

#define GPIO_PUPD_PIN3_OFFSET  (6U)
#define GPIO_PUPD_PIN3_MASK    (0x3UL << REGISTER_FIELD_OFFSET(GPIO, PUPD, PIN3))   /*!< Mask  0x000000C0 */

#define GPIO_PUPD_PIN2_OFFSET  (4U)
#define GPIO_PUPD_PIN2_MASK    (0x3UL << REGISTER_FIELD_OFFSET(GPIO, PUPD, PIN2))   /*!< Mask  0x00000020 */

#define GPIO_PUPD_PIN1_OFFSET  (2U)
#define GPIO_PUPD_PIN1_MASK    (0x3UL << REGISTER_FIELD_OFFSET(GPIO, PUPD, PIN1))   /*!< Mask  0x0000000C */

#define GPIO_PUPD_PIN0_OFFSET  (0U)
#define GPIO_PUPD_PIN0_MASK    (0x3UL << REGISTER_FIELD_OFFSET(GPIO, PUPD, PIN0))   /*!< Mask  0x00000003 */

// Value of pull up or pull down for each GPIO pin
#define GPIO_NOPUPD  (0x0UL)  /*!< Value 0x00000000 */
#define GPIO_PU      (0x1UL)  /*!< Value 0x00000001 */
#define GPIO_PD      (0x2UL)  /*!< Value 0x00000002 */

/*!< Input data register */
#define GPIO_IDATA_PIN15_OFFSET (15U)
#define GPIO_IDATA_PIN15_MASK   (0x1UL << REGISTER_FIELD_OFFSET(GPIO, IDATA, PIN15))  /*!< Mask  0x00008000 */

#define GPIO_IDATA_PIN14_OFFSET (14U)
#define GPIO_IDATA_PIN14_MASK   (0x1UL << REGISTER_FIELD_OFFSET(GPIO, IDATA, PIN14))  /*!< Mask  0x00004000 */

#define GPIO_IDATA_PIN13_OFFSET (13U)
#define GPIO_IDATA_PIN13_MASK   (0x1UL << REGISTER_FIELD_OFFSET(GPIO, IDATA, PIN13))  /*!< Mask  0x00002000 */

#define GPIO_IDATA_PIN12_OFFSET (12U)
#define GPIO_IDATA_PIN12_MASK   (0x1UL << REGISTER_FIELD_OFFSET(GPIO, IDATA, PIN12))  /*!< Mask  0x00001000 */

#define GPIO_IDATA_PIN11_OFFSET (11U)
#define GPIO_IDATA_PIN11_MASK   (0x1UL << REGISTER_FIELD_OFFSET(GPIO, IDATA, PIN11))  /*!< Mask  0x00000800 */

#define GPIO_IDATA_PIN10_OFFSET (10U)
#define GPIO_IDATA_PIN10_MASK   (0x1UL << REGISTER_FIELD_OFFSET(GPIO, IDATA, PIN10))  /*!< Mask  0x00000400 */

#define GPIO_IDATA_PIN9_OFFSET  (9U)
#define GPIO_IDATA_PIN9_MASK    (0x1UL << REGISTER_FIELD_OFFSET(GPIO, IDATA, PIN9))   /*!< Mask  0x00000200 */

#define GPIO_IDATA_PIN8_OFFSET  (8U)
#define GPIO_IDATA_PIN8_MASK    (0x1UL << REGISTER_FIELD_OFFSET(GPIO, IDATA, PIN8))   /*!< Mask  0x00000100 */

#define GPIO_IDATA_PIN7_OFFSET  (7U)
#define GPIO_IDATA_PIN7_MASK    (0x1UL << REGISTER_FIELD_OFFSET(GPIO, IDATA, PIN7))   /*!< Mask  0x00000080 */

#define GPIO_IDATA_PIN6_OFFSET  (6U)
#define GPIO_IDATA_PIN6_MASK    (0x1UL << REGISTER_FIELD_OFFSET(GPIO, IDATA, PIN6))   /*!< Mask  0x00000040 */

#define GPIO_IDATA_PIN5_OFFSET  (5U)
#define GPIO_IDATA_PIN5_MASK    (0x1UL << REGISTER_FIELD_OFFSET(GPIO, IDATA, PIN5))   /*!< Mask  0x00000020 */

#define GPIO_IDATA_PIN4_OFFSET  (4U)
#define GPIO_IDATA_PIN4_MASK    (0x1UL << REGISTER_FIELD_OFFSET(GPIO, IDATA, PIN4))   /*!< Mask  0x00000010 */

#define GPIO_IDATA_PIN3_OFFSET  (3U)
#define GPIO_IDATA_PIN3_MASK    (0x1UL << REGISTER_FIELD_OFFSET(GPIO, IDATA, PIN3))   /*!< Mask  0x00000008 */

#define GPIO_IDATA_PIN2_OFFSET  (2U)
#define GPIO_IDATA_PIN2_MASK    (0x1UL << REGISTER_FIELD_OFFSET(GPIO, IDATA, PIN2))   /*!< Mask  0x00000004 */

#define GPIO_IDATA_PIN1_OFFSET  (1U)
#define GPIO_IDATA_PIN1_MASK    (0x1UL << REGISTER_FIELD_OFFSET(GPIO, IDATA, PIN1))   /*!< Mask  0x00000002 */

#define GPIO_IDATA_PIN0_OFFSET  (0U)
#define GPIO_IDATA_PIN0_MASK    (0x1UL << REGISTER_FIELD_OFFSET(GPIO, IDATA, PIN0))   /*!< Mask  0x00000001 */

/*!< Output data register */
#define GPIO_ODATA_PIN15_OFFSET (15U)
#define GPIO_ODATA_PIN15_MASK   (0x1UL << REGISTER_FIELD_OFFSET(GPIO, ODATA, PIN15))  /*!< Mask  0x00008000 */

#define GPIO_ODATA_PIN14_OFFSET (14U)
#define GPIO_ODATA_PIN14_MASK   (0x1UL << REGISTER_FIELD_OFFSET(GPIO, ODATA, PIN14))  /*!< Mask  0x00004000 */

#define GPIO_ODATA_PIN13_OFFSET (13U)
#define GPIO_ODATA_PIN13_MASK   (0x1UL << REGISTER_FIELD_OFFSET(GPIO, ODATA, PIN13))  /*!< Mask  0x00002000 */

#define GPIO_ODATA_PIN12_OFFSET (12U)
#define GPIO_ODATA_PIN12_MASK   (0x1UL << REGISTER_FIELD_OFFSET(GPIO, ODATA, PIN12))  /*!< Mask  0x00001000 */

#define GPIO_ODATA_PIN11_OFFSET (11U)
#define GPIO_ODATA_PIN11_MASK   (0x1UL << REGISTER_FIELD_OFFSET(GPIO, ODATA, PIN11))  /*!< Mask  0x00000800 */

#define GPIO_ODATA_PIN10_OFFSET (10U)
#define GPIO_ODATA_PIN10_MASK   (0x1UL << REGISTER_FIELD_OFFSET(GPIO, ODATA, PIN10))  /*!< Mask  0x00000400 */

#define GPIO_ODATA_PIN9_OFFSET  (9U)
#define GPIO_ODATA_PIN9_MASK    (0x1UL << REGISTER_FIELD_OFFSET(GPIO, ODATA, PIN9))   /*!< Mask  0x00000200 */

#define GPIO_ODATA_PIN8_OFFSET  (8U)
#define GPIO_ODATA_PIN8_MASK    (0x1UL << REGISTER_FIELD_OFFSET(GPIO, ODATA, PIN8))   /*!< Mask  0x00000100 */

#define GPIO_ODATA_PIN7_OFFSET  (7U)
#define GPIO_ODATA_PIN7_MASK    (0x1UL << REGISTER_FIELD_OFFSET(GPIO, ODATA, PIN7))   /*!< Mask  0x00000080 */

#define GPIO_ODATA_PIN6_OFFSET  (6U)
#define GPIO_ODATA_PIN6_MASK    (0x1UL << REGISTER_FIELD_OFFSET(GPIO, ODATA, PIN6))   /*!< Mask  0x00000040 */

#define GPIO_ODATA_PIN5_OFFSET  (5U)
#define GPIO_ODATA_PIN5_MASK    (0x1UL << REGISTER_FIELD_OFFSET(GPIO, ODATA, PIN5))   /*!< Mask  0x00000020 */

#define GPIO_ODATA_PIN4_OFFSET  (4U)
#define GPIO_ODATA_PIN4_MASK    (0x1UL << REGISTER_FIELD_OFFSET(GPIO, ODATA, PIN4))   /*!< Mask  0x00000010 */

#define GPIO_ODATA_PIN3_OFFSET  (3U)
#define GPIO_ODATA_PIN3_MASK    (0x1UL << REGISTER_FIELD_OFFSET(GPIO, ODATA, PIN3))   /*!< Mask  0x00000008 */

#define GPIO_ODATA_PIN2_OFFSET  (2U)
#define GPIO_ODATA_PIN2_MASK    (0x1UL << REGISTER_FIELD_OFFSET(GPIO, ODATA, PIN2))   /*!< Mask  0x00000004 */

#define GPIO_ODATA_PIN1_OFFSET  (1U)
#define GPIO_ODATA_PIN1_MASK    (0x1UL << REGISTER_FIELD_OFFSET(GPIO, ODATA, PIN1))   /*!< Mask  0x00000002 */

#define GPIO_ODATA_PIN0_OFFSET  (0U)
#define GPIO_ODATA_PIN0_MASK    (0x1UL << REGISTER_FIELD_OFFSET(GPIO, ODATA, PIN0))   /*!< Mask  0x00000001 */

// Value of each GPIO pin
#define GPIO_0  (0x0UL)  /*!< Value 0x00000000 */
#define GPIO_1  (0x1UL)  /*!< Value 0x00000001 */

/*!< Bit set/reset register */
#define GPIO_BSR_RESET15_OFFSET (31U)
#define GPIO_BSR_RESET15_MASK   (0x1UL << REGISTER_FIELD_OFFSET(GPIO, BSR, RESET15))  /*!< Mask  0x80000000 */

#define GPIO_BSR_RESET14_OFFSET (30U)
#define GPIO_BSR_RESET14_MASK   (0x1UL << REGISTER_FIELD_OFFSET(GPIO, BSR, RESET14))  /*!< Mask  0x40000000 */

#define GPIO_BSR_RESET13_OFFSET (29U)
#define GPIO_BSR_RESET13_MASK   (0x1UL << REGISTER_FIELD_OFFSET(GPIO, BSR, RESET13))  /*!< Mask  0x20000000 */

#define GPIO_BSR_RESET12_OFFSET (28U)
#define GPIO_BSR_RESET12_MASK   (0x1UL << REGISTER_FIELD_OFFSET(GPIO, BSR, RESET12))  /*!< Mask  0x10000000 */

#define GPIO_BSR_RESET11_OFFSET (27U)
#define GPIO_BSR_RESET11_MASK   (0x1UL << REGISTER_FIELD_OFFSET(GPIO, BSR, RESET11))  /*!< Mask  0x08000000 */

#define GPIO_BSR_RESET10_OFFSET (26U)
#define GPIO_BSR_RESET10_MASK   (0x1UL << REGISTER_FIELD_OFFSET(GPIO, BSR, RESET10))  /*!< Mask  0x04000000 */

#define GPIO_BSR_RESET9_OFFSET  (25U)
#define GPIO_BSR_RESET9_MASK    (0x1UL << REGISTER_FIELD_OFFSET(GPIO, BSR, RESET9))   /*!< Mask  0x02000000 */

#define GPIO_BSR_RESET8_OFFSET  (24U)
#define GPIO_BSR_RESET8_MASK    (0x1UL << REGISTER_FIELD_OFFSET(GPIO, BSR, RESET8))   /*!< Mask  0x01000000 */

#define GPIO_BSR_RESET7_OFFSET  (23U)
#define GPIO_BSR_RESET7_MASK    (0x1UL << REGISTER_FIELD_OFFSET(GPIO, BSR, RESET7))   /*!< Mask  0x00800000 */

#define GPIO_BSR_RESET6_OFFSET  (22U)
#define GPIO_BSR_RESET6_MASK    (0x1UL << REGISTER_FIELD_OFFSET(GPIO, BSR, RESET6))   /*!< Mask  0x00400000 */

#define GPIO_BSR_RESET5_OFFSET  (21U)
#define GPIO_BSR_RESET5_MASK    (0x1UL << REGISTER_FIELD_OFFSET(GPIO, BSR, RESET5))   /*!< Mask  0x00200000 */

#define GPIO_BSR_RESET4_OFFSET  (20U)
#define GPIO_BSR_RESET4_MASK    (0x1UL << REGISTER_FIELD_OFFSET(GPIO, BSR, RESET4))   /*!< Mask  0x00100000 */

#define GPIO_BSR_RESET3_OFFSET  (19U)
#define GPIO_BSR_RESET3_MASK    (0x1UL << REGISTER_FIELD_OFFSET(GPIO, BSR, RESET3))   /*!< Mask  0x00080000 */

#define GPIO_BSR_RESET2_OFFSET  (18U)
#define GPIO_BSR_RESET2_MASK    (0x1UL << REGISTER_FIELD_OFFSET(GPIO, BSR, RESET2))   /*!< Mask  0x00040000 */

#define GPIO_BSR_RESET1_OFFSET  (17U)
#define GPIO_BSR_RESET1_MASK    (0x1UL << REGISTER_FIELD_OFFSET(GPIO, BSR, RESET1))   /*!< Mask  0x00020000 */

#define GPIO_BSR_RESET0_OFFSET  (16U)
#define GPIO_BSR_RESET0_MASK    (0x1UL << REGISTER_FIELD_OFFSET(GPIO, BSR, RESET0))   /*!< Mask  0x00010000 */

#define GPIO_BSR_SET15_OFFSET   (15U)
#define GPIO_BSR_SET15_MASK     (0x1UL << REGISTER_FIELD_OFFSET(GPIO, BSR, SET15))    /*!< Mask  0x00008000 */

#define GPIO_BSR_SET14_OFFSET   (14U)
#define GPIO_BSR_SET14_MASK     (0x1UL << REGISTER_FIELD_OFFSET(GPIO, BSR, SET14))    /*!< Mask  0x00004000 */

#define GPIO_BSR_SET13_OFFSET   (13U)
#define GPIO_BSR_SET13_MASK     (0x1UL << REGISTER_FIELD_OFFSET(GPIO, BSR, SET13))    /*!< Mask  0x00002000 */

#define GPIO_BSR_SET12_OFFSET   (12U)
#define GPIO_BSR_SET12_MASK     (0x1UL << REGISTER_FIELD_OFFSET(GPIO, BSR, SET12))    /*!< Mask  0x00001000 */

#define GPIO_BSR_SET11_OFFSET   (11U)
#define GPIO_BSR_SET11_MASK     (0x1UL << REGISTER_FIELD_OFFSET(GPIO, BSR, SET11))    /*!< Mask  0x00000800 */

#define GPIO_BSR_SET10_OFFSET   (10U)
#define GPIO_BSR_SET10_MASK     (0x1UL << REGISTER_FIELD_OFFSET(GPIO, BSR, SET10))    /*!< Mask  0x00000400 */

#define GPIO_BSR_SET9_OFFSET    (9U)
#define GPIO_BSR_SET9_MASK      (0x1UL << REGISTER_FIELD_OFFSET(GPIO, BSR, SET9))     /*!< Mask  0x00000200 */

#define GPIO_BSR_SET8_OFFSET    (8U)
#define GPIO_BSR_SET8_MASK      (0x1UL << REGISTER_FIELD_OFFSET(GPIO, BSR, SET8))     /*!< Mask  0x00000100 */

#define GPIO_BSR_SET7_OFFSET    (7U)
#define GPIO_BSR_SET7_MASK      (0x1UL << REGISTER_FIELD_OFFSET(GPIO, BSR, SET7))     /*!< Mask  0x00000080 */

#define GPIO_BSR_SET6_OFFSET    (6U)
#define GPIO_BSR_SET6_MASK      (0x1UL << REGISTER_FIELD_OFFSET(GPIO, BSR, SET6))     /*!< Mask  0x00000040 */

#define GPIO_BSR_SET5_OFFSET    (5U)
#define GPIO_BSR_SET5_MASK      (0x1UL << REGISTER_FIELD_OFFSET(GPIO, BSR, SET5))     /*!< Mask  0x00000020 */

#define GPIO_BSR_SET4_OFFSET    (4U)
#define GPIO_BSR_SET4_MASK      (0x1UL << REGISTER_FIELD_OFFSET(GPIO, BSR, SET4))     /*!< Mask  0x00000010 */

#define GPIO_BSR_SET3_OFFSET    (3U)
#define GPIO_BSR_SET3_MASK      (0x1UL << REGISTER_FIELD_OFFSET(GPIO, BSR, SET3))     /*!< Mask  0x00000008 */

#define GPIO_BSR_SET2_OFFSET    (2U)
#define GPIO_BSR_SET2_MASK      (0x1UL << REGISTER_FIELD_OFFSET(GPIO, BSR, SET2))     /*!< Mask  0x00000004 */

#define GPIO_BSR_SET1_OFFSET    (1U)
#define GPIO_BSR_SET1_MASK      (0x1UL << REGISTER_FIELD_OFFSET(GPIO, BSR, SET1))     /*!< Mask  0x00000002 */

#define GPIO_BSR_SET0_OFFSET    (0U)
#define GPIO_BSR_SET0_MASK      (0x1UL << REGISTER_FIELD_OFFSET(GPIO, BSR, SET0))     /*!< Mask  0x00000001 */

// Value of reset triggering for each GPIO pin
#define GPIO_NORESETODATA  (0x0UL)  /*!< Value 0x00000000 */
#define GPIO_RESETODATA    (0x1UL)  /*!< Value 0x00000001 */

// Value of set triggering for each GPIO pin
#define GPIO_NOSETODATA  (0x0UL)  /*!< Value 0x00000000 */
#define GPIO_SETODATA    (0x1UL)  /*!< Value 0x00000001 */

/*!< Port configuration lock register */
#define GPIO_CFGLOCK_LOCKKEY_OFFSET    (16U)
#define GPIO_CFGLOCK_LOCKKEY_MASK      (0x1UL << REGISTER_FIELD_OFFSET(GPIO, CFGLOCK, LOCKKEY))  /*!< Mask  0x00010000 */
#define GPIO_CFGLOCK_LOCKKEY_NOTACTIVE (0x0UL)                                                   /*!< Mask  0x00000000 */
#define GPIO_CFGLOCK_LOCKKEY_ACTIVE    (0x1UL)                                                   /*!< Mask  0x00000001 */

#define GPIO_CFGLOCK_PIN15_OFFSET      (15U)
#define GPIO_CFGLOCK_PIN15_MASK        (0x1UL << REGISTER_FIELD_OFFSET(GPIO, CFGLOCK, PIN15))    /*!< Mask  0x00008000 */

#define GPIO_CFGLOCK_PIN14_OFFSET      (14U)
#define GPIO_CFGLOCK_PIN14_MASK        (0x1UL << REGISTER_FIELD_OFFSET(GPIO, CFGLOCK, PIN14))    /*!< Mask  0x00004000 */

#define GPIO_CFGLOCK_PIN13_OFFSET      (13U)
#define GPIO_CFGLOCK_PIN13_MASK        (0x1UL << REGISTER_FIELD_OFFSET(GPIO, CFGLOCK, PIN13))    /*!< Mask  0x00002000 */

#define GPIO_CFGLOCK_PIN12_OFFSET      (12U)
#define GPIO_CFGLOCK_PIN12_MASK        (0x1UL << REGISTER_FIELD_OFFSET(GPIO, CFGLOCK, PIN12))    /*!< Mask  0x00001000 */

#define GPIO_CFGLOCK_PIN11_OFFSET      (11U)
#define GPIO_CFGLOCK_PIN11_MASK        (0x1UL << REGISTER_FIELD_OFFSET(GPIO, CFGLOCK, PIN11))    /*!< Mask  0x00000800 */

#define GPIO_CFGLOCK_PIN10_OFFSET      (10U)
#define GPIO_CFGLOCK_PIN10_MASK        (0x1UL << REGISTER_FIELD_OFFSET(GPIO, CFGLOCK, PIN10))    /*!< Mask  0x00000400 */

#define GPIO_CFGLOCK_PIN9_OFFSET       (9U)
#define GPIO_CFGLOCK_PIN9_MASK         (0x1UL << REGISTER_FIELD_OFFSET(GPIO, CFGLOCK, PIN9))     /*!< Mask  0x00000200 */

#define GPIO_CFGLOCK_PIN8_OFFSET       (8U)
#define GPIO_CFGLOCK_PIN8_MASK         (0x1UL << REGISTER_FIELD_OFFSET(GPIO, CFGLOCK, PIN8))     /*!< Mask  0x00000100 */

#define GPIO_CFGLOCK_PIN7_OFFSET       (7U)
#define GPIO_CFGLOCK_PIN7_MASK         (0x1UL << REGISTER_FIELD_OFFSET(GPIO, CFGLOCK, PIN7))     /*!< Mask  0x00000080 */

#define GPIO_CFGLOCK_PIN6_OFFSET       (6U)
#define GPIO_CFGLOCK_PIN6_MASK         (0x1UL << REGISTER_FIELD_OFFSET(GPIO, CFGLOCK, PIN6))     /*!< Mask  0x00000040 */

#define GPIO_CFGLOCK_PIN5_OFFSET       (5U)
#define GPIO_CFGLOCK_PIN5_MASK         (0x1UL << REGISTER_FIELD_OFFSET(GPIO, CFGLOCK, PIN5))     /*!< Mask  0x00000020 */

#define GPIO_CFGLOCK_PIN4_OFFSET       (4U)
#define GPIO_CFGLOCK_PIN4_MASK         (0x1UL << REGISTER_FIELD_OFFSET(GPIO, CFGLOCK, PIN4))     /*!< Mask  0x00000010 */

#define GPIO_CFGLOCK_PIN3_OFFSET       (3U)
#define GPIO_CFGLOCK_PIN3_MASK         (0x1UL << REGISTER_FIELD_OFFSET(GPIO, CFGLOCK, PIN3))     /*!< Mask  0x00000008 */

#define GPIO_CFGLOCK_PIN2_OFFSET       (2U)
#define GPIO_CFGLOCK_PIN2_MASK         (0x1UL << REGISTER_FIELD_OFFSET(GPIO, CFGLOCK, PIN2))     /*!< Mask  0x00000004 */

#define GPIO_CFGLOCK_PIN1_OFFSET       (1U)
#define GPIO_CFGLOCK_PIN1_MASK         (0x1UL << REGISTER_FIELD_OFFSET(GPIO, CFGLOCK, PIN1))     /*!< Mask  0x00000002 */

#define GPIO_CFGLOCK_PIN0_OFFSET       (0U)
#define GPIO_CFGLOCK_PIN0_MASK         (0x1UL << REGISTER_FIELD_OFFSET(GPIO, CFGLOCK, PIN0))     /*!< Mask  0x00000001 */

// Value of lock configuration for each GPIO pin
#define GPIO_CFGUNLOCKED  (0x0UL)  /*!< Mask  0x00000000 */
#define GPIO_CFGLOCKED    (0x1UL)  /*!< Mask  0x00000001 */

/*!< Alternate function register */
#define GPIO_ALTFUNC_PIN15_OFFSET (28U)
#define GPIO_ALTFUNC_PIN15_MASK   (0xFUL << REGISTER_FIELD_OFFSET(GPIO, ALTFUNC, PIN15))  /*!< Mask  0xF0000000 */

#define GPIO_ALTFUNC_PIN14_OFFSET (24U)
#define GPIO_ALTFUNC_PIN14_MASK   (0xFUL << REGISTER_FIELD_OFFSET(GPIO, ALTFUNC, PIN14))  /*!< Mask  0x0F000000 */

#define GPIO_ALTFUNC_PIN13_OFFSET (20U)
#define GPIO_ALTFUNC_PIN13_MASK   (0xFUL << REGISTER_FIELD_OFFSET(GPIO, ALTFUNC, PIN13))  /*!< Mask  0x00F00000 */

#define GPIO_ALTFUNC_PIN12_OFFSET (16U)
#define GPIO_ALTFUNC_PIN12_MASK   (0xFUL << REGISTER_FIELD_OFFSET(GPIO, ALTFUNC, PIN12))  /*!< Mask  0x000F0000 */

#define GPIO_ALTFUNC_PIN11_OFFSET (12U)
#define GPIO_ALTFUNC_PIN11_MASK   (0xFUL << REGISTER_FIELD_OFFSET(GPIO, ALTFUNC, PIN11))  /*!< Mask  0x0000F000 */

#define GPIO_ALTFUNC_PIN10_OFFSET (8U)
#define GPIO_ALTFUNC_PIN10_MASK   (0xFUL << REGISTER_FIELD_OFFSET(GPIO, ALTFUNC, PIN10))  /*!< Mask  0x00000F00 */

#define GPIO_ALTFUNC_PIN9_OFFSET  (4U)
#define GPIO_ALTFUNC_PIN9_MASK    (0xFUL << REGISTER_FIELD_OFFSET(GPIO, ALTFUNC, PIN9))   /*!< Mask  0x000000F0 */

#define GPIO_ALTFUNC_PIN8_OFFSET  (0U)
#define GPIO_ALTFUNC_PIN8_MASK    (0xFUL << REGISTER_FIELD_OFFSET(GPIO, ALTFUNC, PIN8))   /*!< Mask  0x0000000F */

#define GPIO_ALTFUNC_PIN7_OFFSET  (28U)
#define GPIO_ALTFUNC_PIN7_MASK    (0xFUL << REGISTER_FIELD_OFFSET(GPIO, ALTFUNC, PIN7))   /*!< Mask  0xF0000000 */

#define GPIO_ALTFUNC_PIN6_OFFSET  (24U)
#define GPIO_ALTFUNC_PIN6_MASK    (0xFUL << REGISTER_FIELD_OFFSET(GPIO, ALTFUNC, PIN6))   /*!< Mask  0x0F000000 */

#define GPIO_ALTFUNC_PIN5_OFFSET  (20U)
#define GPIO_ALTFUNC_PIN5_MASK    (0xFUL << REGISTER_FIELD_OFFSET(GPIO, ALTFUNC, PIN5))   /*!< Mask  0x00F00000 */

#define GPIO_ALTFUNC_PIN4_OFFSET  (16U)
#define GPIO_ALTFUNC_PIN4_MASK    (0xFUL << REGISTER_FIELD_OFFSET(GPIO, ALTFUNC, PIN4))   /*!< Mask  0x000F0000 */

#define GPIO_ALTFUNC_PIN3_OFFSET  (12U)
#define GPIO_ALTFUNC_PIN3_MASK    (0xFUL << REGISTER_FIELD_OFFSET(GPIO, ALTFUNC, PIN3))   /*!< Mask  0x0000F000 */

#define GPIO_ALTFUNC_PIN2_OFFSET  (8U)
#define GPIO_ALTFUNC_PIN2_MASK    (0xFUL << REGISTER_FIELD_OFFSET(GPIO, ALTFUNC, PIN2))   /*!< Mask  0x00000F00 */

#define GPIO_ALTFUNC_PIN1_OFFSET  (4U)
#define GPIO_ALTFUNC_PIN1_MASK    (0xFUL << REGISTER_FIELD_OFFSET(GPIO, ALTFUNC, PIN1))   /*!< Mask  0x000000F0 */

#define GPIO_ALTFUNC_PIN0_OFFSET  (0U)
#define GPIO_ALTFUNC_PIN0_MASK    (0xFUL << REGISTER_FIELD_OFFSET(GPIO, ALTFUNC, PIN0))   /*!< Mask  0x0000000F */

// Value of alternative function for each GPIO pin
#define GPIO_ALTFUNC0   (0x0UL)  /*!< Value 0x00000000 */
#define GPIO_ALTFUNC1   (0x1UL)  /*!< Value 0x00000001 */
#define GPIO_ALTFUNC2   (0x2UL)  /*!< Value 0x00000002 */
#define GPIO_ALTFUNC3   (0x3UL)  /*!< Value 0x00000003 */
#define GPIO_ALTFUNC4   (0x4UL)  /*!< Value 0x00000004 */
#define GPIO_ALTFUNC5   (0x5UL)  /*!< Value 0x00000005 */
#define GPIO_ALTFUNC6   (0x6UL)  /*!< Value 0x00000006 */
#define GPIO_ALTFUNC7   (0x7UL)  /*!< Value 0x00000007 */
#define GPIO_ALTFUNC8   (0x8UL)  /*!< Value 0x00000008 */
#define GPIO_ALTFUNC9   (0x9UL)  /*!< Value 0x00000009 */
#define GPIO_ALTFUNC10  (0xAUL)  /*!< Value 0x0000000A */
#define GPIO_ALTFUNC11  (0xBUL)  /*!< Value 0x0000000B */
#define GPIO_ALTFUNC12  (0xCUL)  /*!< Value 0x0000000C */
#define GPIO_ALTFUNC13  (0xDUL)  /*!< Value 0x0000000D */
#define GPIO_ALTFUNC14  (0xEUL)  /*!< Value 0x0000000E */
#define GPIO_ALTFUNC15  (0xFUL)  /*!< Value 0x0000000F */

#define GPIO_OFFSET 0x0
#define GPIO_BASE (D3_AHB4_BASE + GPIO_OFFSET)
#define GPIO_ADDRESS_RANGE 0x3FF

/*!< GPIO registers for GPIO A */
#define GPIO_GPIOA_OFFSET (0*GPIO_ADDRESS_RANGE)
#define GPIO_GPIOA_BASE OFFSET_ADDRESS(GPIO_BASE, GPIO_GPIOA_OFFSET)
#define GPIO_GPIOA REGISTER_PTR(gpio_regs, GPIO_GPIOA_BASE)

/*!< GPIO registers for GPIO B */
#define GPIO_GPIOB_OFFSET (1*GPIO_ADDRESS_RANGE)
#define GPIO_GPIOB_BASE OFFSET_ADDRESS(GPIO_BASE, GPIO_GPIOB_OFFSET)
#define GPIO_GPIOB REGISTER_PTR(gpio_regs, GPIO_GPIOB_BASE)

/*!< GPIO registers for GPIO C */
#define GPIO_GPIOC_OFFSET (2*GPIO_ADDRESS_RANGE)
#define GPIO_GPIOC_BASE OFFSET_ADDRESS(GPIO_BASE, GPIO_GPIOC_OFFSET)
#define GPIO_GPIOC REGISTER_PTR(gpio_regs, GPIO_GPIOC_BASE)

/*!< GPIO registers for GPIO D */
#define GPIO_GPIOD_OFFSET (3*GPIO_ADDRESS_RANGE)
#define GPIO_GPIOD_BASE OFFSET_ADDRESS(GPIO_BASE, GPIO_GPIOD_OFFSET)
#define GPIO_GPIOD REGISTER_PTR(gpio_regs, GPIO_GPIOD_BASE)

/*!< GPIO registers for GPIO E */
#define GPIO_GPIOE_OFFSET (4*GPIO_ADDRESS_RANGE)
#define GPIO_GPIOE_BASE OFFSET_ADDRESS(GPIO_BASE, GPIO_GPIOE_OFFSET)
#define GPIO_GPIOE REGISTER_PTR(gpio_regs, GPIO_GPIOE_BASE)

/*!< GPIO registers for GPIO F */
#define GPIO_GPIOF_OFFSET (5*GPIO_ADDRESS_RANGE)
#define GPIO_GPIOF_BASE OFFSET_ADDRESS(GPIO_BASE, GPIO_GPIOF_OFFSET)
#define GPIO_GPIOF REGISTER_PTR(gpio_regs, GPIO_GPIOF_BASE)

/*!< GPIO registers for GPIO G */
#define GPIO_GPIOG_OFFSET (6*GPIO_ADDRESS_RANGE)
#define GPIO_GPIOG_BASE OFFSET_ADDRESS(GPIO_BASE, GPIO_GPIOG_OFFSET)
#define GPIO_GPIOG REGISTER_PTR(gpio_regs, GPIO_GPIOG_BASE)

/*!< GPIO registers for GPIO H */
#define GPIO_GPIOH_OFFSET (7*GPIO_ADDRESS_RANGE)
#define GPIO_GPIOH_BASE OFFSET_ADDRESS(GPIO_BASE, GPIO_GPIOH_OFFSET)
#define GPIO_GPIOH REGISTER_PTR(gpio_regs, GPIO_GPIOH_BASE)

/*!< GPIO registers for GPIO I */
#define GPIO_GPIOI_OFFSET (8*GPIO_ADDRESS_RANGE)
#define GPIO_GPIOI_BASE OFFSET_ADDRESS(GPIO_BASE, GPIO_GPIOI_OFFSET)
#define GPIO_GPIOI REGISTER_PTR(gpio_regs, GPIO_GPIOI_BASE)

/*!< GPIO registers for GPIO J */
#define GPIO_GPIOJ_OFFSET (9*GPIO_ADDRESS_RANGE)
#define GPIO_GPIOJ_BASE OFFSET_ADDRESS(GPIO_BASE, GPIO_GPIOJ_OFFSET)
#define GPIO_GPIOJ REGISTER_PTR(gpio_regs, GPIO_GPIOJ_BASE)

/*!< GPIO registers for GPIO K */
#define GPIO_GPIOK_OFFSET (10*GPIO_ADDRESS_RANGE)
#define GPIO_GPIOK_BASE OFFSET_ADDRESS(GPIO_BASE, GPIO_GPIOK_OFFSET)
#define GPIO_GPIOK REGISTER_PTR(gpio_regs, GPIO_GPIOK_BASE)

/** @} */ // End of GPIO group

/** @} */ // End of RegisterGroup group

#endif // GPIO_REGISTERS_H
