/**
 * @copyright
 * @file boot.c
 * @author Andrea Gianarda
 * @date 26th of February 2021
 * @brief Boot functions
 */

#include "registers/rcc.h"
#include "registers/flash.h"

void systemInit(void) {

	// Reset value of flash read latency is 7, hence start the procedure to increase the clock frequency if too low
	if (GET_FIELD_VALUE(FLASH_BANK1->ACCESSCTRL, FLASH, ACCESSCTRL, LATENCY) < FLASH_LATENCY_7WAITSTATE) {
		MODIFY_FIELD(FLASH_BANK1->ACCESSCTRL, FLASH, ACCESSCTRL, LATENCY, FLASH_LATENCY_7WAITSTATE);
	}

	// Enable HSI only
	//MODIFY_REG(RCC_COMMON->SRCCTRL, REGISTER_FIELD_SETTER(RCC, SRCCTRL, HSIEN, RCC_SRCCTRL_HSIEN_ENABLE))
	MODIFY_FIELD(RCC_COMMON->SRCCTRL, RCC, SRCCTRL, HSIEN, RCC_CLK_ENABLE);

	CLEAR_BITS(RCC_COMMON->SRCCTRL, (
		REGISTER_FIELD_SETTER(RCC, SRCCTRL, HSISMEN,   RCC_CLK_DISABLE    ) |
		REGISTER_FIELD_SETTER(RCC, SRCCTRL, HSIDIV,    RCC_HSIDIV_BYPASS  ) |
		REGISTER_FIELD_SETTER(RCC, SRCCTRL, CSIEN,     RCC_CLK_DISABLE    ) |
		REGISTER_FIELD_SETTER(RCC, SRCCTRL, CSISMEN,   RCC_CLK_DISABLE    ) |
		REGISTER_FIELD_SETTER(RCC, SRCCTRL, HSI48EN,   RCC_CLK_DISABLE    ) |
		REGISTER_FIELD_SETTER(RCC, SRCCTRL, HSEEN,     RCC_CLK_DISABLE    ) |
		REGISTER_FIELD_SETTER(RCC, SRCCTRL, HSEBYPASS, RCC_HSE_NOBYPASS   ) |
		REGISTER_FIELD_SETTER(RCC, SRCCTRL, HSECSSEN,  RCC_CLK_DISABLE    ) |
		REGISTER_FIELD_SETTER(RCC, SRCCTRL, PLL1EN,    RCC_PLL_DISABLE    ) |
		REGISTER_FIELD_SETTER(RCC, SRCCTRL, PLL2EN,    RCC_PLL_DISABLE    ) |
		REGISTER_FIELD_SETTER(RCC, SRCCTRL, PLL3EN,    RCC_PLL_DISABLE    ) )
	);

	// Clock configuration
	MODIFY_REG(RCC_COMMON->CLKCFG, (
		REGISTER_FIELD_SETTER(RCC, CLKCFG, MCO2SEL,        RCC_MCO2_SYSCLK          ) |
		REGISTER_FIELD_SETTER(RCC, CLKCFG, MCO2PRE,        RCC_MCOPRE_DISABLE       ) |
		REGISTER_FIELD_SETTER(RCC, CLKCFG, MCO1SEL,        RCC_MCO1_HSI             ) |
		REGISTER_FIELD_SETTER(RCC, CLKCFG, MCO1PRE,        RCC_MCOPRE_DISABLE       ) |
		REGISTER_FIELD_SETTER(RCC, CLKCFG, TIMERPRE,       RCC_TIMERPRE_MUL2        ) |
		REGISTER_FIELD_SETTER(RCC, CLKCFG, HRTIMERPRESEL,  RCC_HRTIMERPRE_TIMERS    ) |
		REGISTER_FIELD_SETTER(RCC, CLKCFG, RTCPRE,         RCC_RTCPRE_NOCLK_DEFAULT ) |
		REGISTER_FIELD_SETTER(RCC, CLKCFG, KERCLKEXITSTOP, RCC_KERCLKEXITSTOP_HSI   ) |
		REGISTER_FIELD_SETTER(RCC, CLKCFG, SYSCLKEXITSTOP, RCC_SYSCLKEXITSTOP_HSI   ) |
		REGISTER_FIELD_SETTER(RCC, CLKCFG, SYSCLKSEL,      RCC_SYSCLK_HSI           ) )
	);

	// Reset value of flash read latency is 7, hence conclude the procedure to decrease the clock frequency if too high
	if (GET_FIELD_VALUE(FLASH_BANK1->ACCESSCTRL, FLASH, ACCESSCTRL, LATENCY) > FLASH_LATENCY_7WAITSTATE) {
		MODIFY_FIELD(FLASH_BANK1->ACCESSCTRL, FLASH, ACCESSCTRL, LATENCY, FLASH_LATENCY_7WAITSTATE);
	}

	// Set HSI clock trimming to 0x40
	MODIFY_FIELD(RCC_COMMON->HSICFG, RCC, HSICFG, HSITRIM, 0x40);

	// D1 clock configuration
	MODIFY_REG(RCC_COMMON->D1CLKCFG, (
		REGISTER_FIELD_SETTER(RCC, D1CLKCFG, COREPRE, RCC_COREPRE_BYPASS ) |
		REGISTER_FIELD_SETTER(RCC, D1CLKCFG, APB3PRE, RCC_APBPRE_BYPASS  ) |
		REGISTER_FIELD_SETTER(RCC, D1CLKCFG, AHBPRE,  RCC_AHBPRE_BYPASS  ) )
	);

	// D2 clock configuration
	MODIFY_REG(RCC_COMMON->D2CLKCFG, (
		REGISTER_FIELD_SETTER(RCC, D2CLKCFG, APB2PRE, RCC_APBPRE_BYPASS ) |
		REGISTER_FIELD_SETTER(RCC, D2CLKCFG, APB1PRE, RCC_APBPRE_BYPASS ) )
	);

	// D3 clock configuration
	MODIFY_REG(RCC_COMMON->D3CLKCFG,
		REGISTER_FIELD_SETTER(RCC, D3CLKCFG, APB4PRE, RCC_APBPRE_BYPASS )
	);

	// PLL clock selection
	MODIFY_REG(RCC_COMMON->PLLCLKSEL, (
		REGISTER_FIELD_SETTER(RCC, PLLCLKSEL, PLL3PRE, RCC_PLLPRE_DIV32 ) |
		REGISTER_FIELD_SETTER(RCC, PLLCLKSEL, PLL2PRE, RCC_PLLPRE_DIV32 ) |
		REGISTER_FIELD_SETTER(RCC, PLLCLKSEL, PLL1PRE, RCC_PLLPRE_DIV32 ) |
		REGISTER_FIELD_SETTER(RCC, PLLCLKSEL, PLLSRC,  RCC_PLLSRC_HSI   ) )
	);

	// PLL configuration
	MODIFY_REG(RCC_COMMON->PLLCFG, (
		REGISTER_FIELD_SETTER(RCC, PLLCFG, PLL3DIVR,      RCC_PLLDIVR_ENABLE      ) |
		REGISTER_FIELD_SETTER(RCC, PLLCFG, PLL3DIVQ,      RCC_PLLDIVQ_ENABLE      ) |
		REGISTER_FIELD_SETTER(RCC, PLLCFG, PLL3DIVP,      RCC_PLLDIVP_ENABLE      ) |
		REGISTER_FIELD_SETTER(RCC, PLLCFG, PLL2DIVR,      RCC_PLLDIVR_ENABLE      ) |
		REGISTER_FIELD_SETTER(RCC, PLLCFG, PLL2DIVQ,      RCC_PLLDIVQ_ENABLE      ) |
		REGISTER_FIELD_SETTER(RCC, PLLCFG, PLL2DIVP,      RCC_PLLDIVP_ENABLE      ) |
		REGISTER_FIELD_SETTER(RCC, PLLCFG, PLL1DIVR,      RCC_PLLDIVR_ENABLE      ) |
		REGISTER_FIELD_SETTER(RCC, PLLCFG, PLL1DIVQ,      RCC_PLLDIVQ_ENABLE      ) |
		REGISTER_FIELD_SETTER(RCC, PLLCFG, PLL1DIVP,      RCC_PLLDIVP_ENABLE      ) |
		REGISTER_FIELD_SETTER(RCC, PLLCFG, PLL3FREQRANGE, RCC_PLLFREQRANGE_1_2MHZ ) |
		REGISTER_FIELD_SETTER(RCC, PLLCFG, PLL3VCOSEL,    RCC_PLLVCOSEL_WIDE      ) |
		REGISTER_FIELD_SETTER(RCC, PLLCFG, PLL3FRAC,      RCC_PLLFRAC_DISABLE     ) |
		REGISTER_FIELD_SETTER(RCC, PLLCFG, PLL2FREQRANGE, RCC_PLLFREQRANGE_1_2MHZ ) |
		REGISTER_FIELD_SETTER(RCC, PLLCFG, PLL2VCOSEL,    RCC_PLLVCOSEL_WIDE      ) |
		REGISTER_FIELD_SETTER(RCC, PLLCFG, PLL2FRAC,      RCC_PLLFRAC_DISABLE     ) |
		REGISTER_FIELD_SETTER(RCC, PLLCFG, PLL1FREQRANGE, RCC_PLLFREQRANGE_1_2MHZ ) |
		REGISTER_FIELD_SETTER(RCC, PLLCFG, PLL1VCOSEL,    RCC_PLLVCOSEL_WIDE      ) |
		REGISTER_FIELD_SETTER(RCC, PLLCFG, PLL1FRAC,      RCC_PLLFRAC_DISABLE     ) )
	);

	// PLL1 divider configuration
	MODIFY_REG(RCC_COMMON->PLL1DIV, (
		REGISTER_FIELD_SETTER(RCC, PLLDIV, DIVR, RCC_PLLDIV2   ) |
		REGISTER_FIELD_SETTER(RCC, PLLDIV, DIVQ, RCC_PLLDIV2   ) |
		REGISTER_FIELD_SETTER(RCC, PLLDIV, DIVP, RCC_PLLDIV2   ) |
		REGISTER_FIELD_SETTER(RCC, PLLDIV, DIVN, RCC_PLLDIV129 ) )
	);

	// PLL1 fractional divider configuration
	MODIFY_REG(RCC_COMMON->PLL1FRACDIV, (
		REGISTER_FIELD_SETTER(RCC, PLLFRACDIV, FRACN, 0x0UL ) )
	);

	// PLL2 divider configuration
	MODIFY_REG(RCC_COMMON->PLL2DIV, (
		REGISTER_FIELD_SETTER(RCC, PLLDIV, DIVR, RCC_PLLDIV2   ) |
		REGISTER_FIELD_SETTER(RCC, PLLDIV, DIVQ, RCC_PLLDIV2   ) |
		REGISTER_FIELD_SETTER(RCC, PLLDIV, DIVP, RCC_PLLDIV2   ) |
		REGISTER_FIELD_SETTER(RCC, PLLDIV, DIVN, RCC_PLLDIV129 ) )
	);

	// PLL2 fractional divider configuration
	MODIFY_REG(RCC_COMMON->PLL2FRACDIV, (
		REGISTER_FIELD_SETTER(RCC, PLLFRACDIV, FRACN, 0x0UL ) )
	);

	// PLL3 divider configuration
	MODIFY_REG(RCC_COMMON->PLL3DIV, (
		REGISTER_FIELD_SETTER(RCC, PLLDIV, DIVR, RCC_PLLDIV2   ) |
		REGISTER_FIELD_SETTER(RCC, PLLDIV, DIVQ, RCC_PLLDIV2   ) |
		REGISTER_FIELD_SETTER(RCC, PLLDIV, DIVP, RCC_PLLDIV2   ) |
		REGISTER_FIELD_SETTER(RCC, PLLDIV, DIVN, RCC_PLLDIV129 ) )
	);

	// PLL3 fractional divider configuration
	MODIFY_REG(RCC_COMMON->PLL3FRACDIV, (
		REGISTER_FIELD_SETTER(RCC, PLLFRACDIV, FRACN, 0x0UL ) )
	);

	// Disable interrupts
	MODIFY_REG(RCC_COMMON->CLKINTEN, (
		REGISTER_FIELD_SETTER(RCC, CLKINTEN, LSECLKSEC, RCC_CLKINT_DISABLE ) |
		REGISTER_FIELD_SETTER(RCC, CLKINTEN, PLL3RDY,   RCC_CLKINT_DISABLE ) |
		REGISTER_FIELD_SETTER(RCC, CLKINTEN, PLL2RDY,   RCC_CLKINT_DISABLE ) |
		REGISTER_FIELD_SETTER(RCC, CLKINTEN, PLL1RDY,   RCC_CLKINT_DISABLE ) |
		REGISTER_FIELD_SETTER(RCC, CLKINTEN, HSI48RDY,  RCC_CLKINT_DISABLE ) |
		REGISTER_FIELD_SETTER(RCC, CLKINTEN, CSIRDY,    RCC_CLKINT_DISABLE ) |
		REGISTER_FIELD_SETTER(RCC, CLKINTEN, HSERDY,    RCC_CLKINT_DISABLE ) |
		REGISTER_FIELD_SETTER(RCC, CLKINTEN, HSIRDY,    RCC_CLKINT_DISABLE ) |
		REGISTER_FIELD_SETTER(RCC, CLKINTEN, LSERDY,    RCC_CLKINT_DISABLE ) |
		REGISTER_FIELD_SETTER(RCC, CLKINTEN, LSIRDY,    RCC_CLKINT_DISABLE ) )
	);

}
