/**
 * @copyright
 * @file boot.c
 * @author Andrea Gianarda
 * @date 26th of February 2021
 * @brief Boot functions
 */

#include "registers/rcc.h"
#include "registers/flash.h"

void systemInit(void) {

	// Enable HSI only
	//MODIFY_REG(RCC_COMMON->SRCCTRL, REGISTER_FIELD_SETTER(RCC, SRCCTRL, HSIEN, RCC_SRCCTRL_HSIEN_ENABLE))
	MODIFY_FIELD(RCC_COMMON->SRCCTRL, RCC, SRCCTRL, HSIEN, RCC_SRCCTRL_HSIEN_ENABLE);

	CLEAR_BITS(RCC_COMMON->SRCCTRL, (
		REGISTER_FIELD_SETTER(RCC, SRCCTRL, HSISMEN,   RCC_SRCCTRL_HSISMEN_DISABLE   ) |
		REGISTER_FIELD_SETTER(RCC, SRCCTRL, HSIDIV,    RCC_SRCCTRL_HSIDIV_BYPASS     ) |
		REGISTER_FIELD_SETTER(RCC, SRCCTRL, CSIEN,     RCC_SRCCTRL_CSIEN_DISABLE     ) |
		REGISTER_FIELD_SETTER(RCC, SRCCTRL, CSISMEN,   RCC_SRCCTRL_CSISMEN_DISABLE   ) |
		REGISTER_FIELD_SETTER(RCC, SRCCTRL, HSI48EN,   RCC_SRCCTRL_HSI48EN_DISABLE   ) |
		REGISTER_FIELD_SETTER(RCC, SRCCTRL, HSEEN,     RCC_SRCCTRL_HSEEN_DISABLE     ) |
		REGISTER_FIELD_SETTER(RCC, SRCCTRL, HSEBYPASS, RCC_SRCCTRL_HSEBYPASS_DISABLE ) |
		REGISTER_FIELD_SETTER(RCC, SRCCTRL, HSECSSEN,  RCC_SRCCTRL_HSECSSEN_DISABLE  ) |
		REGISTER_FIELD_SETTER(RCC, SRCCTRL, PLL1EN,    RCC_SRCCTRL_PLL1EN_DISABLE    ) |
		REGISTER_FIELD_SETTER(RCC, SRCCTRL, PLL2EN,    RCC_SRCCTRL_PLL2EN_DISABLE    ) |
		REGISTER_FIELD_SETTER(RCC, SRCCTRL, PLL3EN,    RCC_SRCCTRL_PLL3EN_DISABLE    ) )
	);

	MODIFY_REG(RCC_COMMON->CLKCFG, (
		REGISTER_FIELD_SETTER(RCC, CLKCFG, MCO2SEL,       RCC_CLKCFG_MCO2SEL_SYSCLK       ) |
		REGISTER_FIELD_SETTER(RCC, CLKCFG, MCO2PRE,       RCC_CLKCFG_MCO2PRE_DISABLE      ) |
		REGISTER_FIELD_SETTER(RCC, CLKCFG, MCO1SEL,       RCC_CLKCFG_MCO1SEL_HSI          ) |
		REGISTER_FIELD_SETTER(RCC, CLKCFG, MCO1PRE,       RCC_CLKCFG_MCO1PRE_DISABLE      ) |
		REGISTER_FIELD_SETTER(RCC, CLKCFG, TIMERPRE,      RCC_CLKCFG_TIMERPRE_MUL2        ) |
		REGISTER_FIELD_SETTER(RCC, CLKCFG, HRTIMERSEL,    RCC_CLKCFG_HRTIMERSEL_TIMERS    ) |
		REGISTER_FIELD_SETTER(RCC, CLKCFG, RTCPRE,        RCC_CLKCFG_RTCPRE_NOCLK_DEFAULT ) |
		REGISTER_FIELD_SETTER(RCC, CLKCFG, KERCLKSYSSTOP, RCC_CLKCFG_KERCLKSYSSTOP_HSI    ) |
		REGISTER_FIELD_SETTER(RCC, CLKCFG, SYSCLKSYSSTOP, RCC_CLKCFG_SYSCLKSYSSTOP_HSI    ) |
		REGISTER_FIELD_SETTER(RCC, CLKCFG, SYSCLKSEL,     RCC_CLKCFG_SYSCLKSEL_HSI        ) )
	);

	// RCC registers can be accesses with 0 to 7 wait states
	// Hence if the number of wait states is higher than 7, bring it down to 7 which is the reset value
	if (GET_FIELD_VALUE(FLASH_BANK1->ACCESSCTRL, FLASH, ACCESSCTRL, LATENCY) > FLASH_ACCESSCTRL_LATENCY_7WAITSTATE) {
		MODIFY_FIELD(FLASH_BANK1->ACCESSCTRL, FLASH, ACCESSCTRL, LATENCY, FLASH_ACCESSCTRL_LATENCY_7WAITSTATE);
	}

	// Set HSI clock trimming to 0x40
	MODIFY_FIELD(RCC_COMMON->HSICFG, RCC, HSICFG, HSITRIM, 0x40);

	// Clock configuration
	MODIFY_REG(RCC_COMMON->CLKCFG, (
		REGISTER_FIELD_SETTER(RCC, CLKCFG, MCO2SEL,       RCC_CLKCFG_MCO2SEL_SYSCLK       ) |
		REGISTER_FIELD_SETTER(RCC, CLKCFG, MCO2PRE,       RCC_CLKCFG_MCO2PRE_DISABLE      ) |
		REGISTER_FIELD_SETTER(RCC, CLKCFG, MCO1SEL,       RCC_CLKCFG_MCO1SEL_HSI          ) |
		REGISTER_FIELD_SETTER(RCC, CLKCFG, MCO1PRE,       RCC_CLKCFG_MCO1PRE_DISABLE      ) |
		REGISTER_FIELD_SETTER(RCC, CLKCFG, TIMERPRE,      RCC_CLKCFG_TIMERPRE_MUL2        ) |
		REGISTER_FIELD_SETTER(RCC, CLKCFG, HRTIMERSEL,    RCC_CLKCFG_HRTIMERSEL_TIMERS    ) |
		REGISTER_FIELD_SETTER(RCC, CLKCFG, RTCPRE,        RCC_CLKCFG_RTCPRE_NOCLK_DEFAULT ) |
		REGISTER_FIELD_SETTER(RCC, CLKCFG, KERCLKSYSSTOP, RCC_CLKCFG_KERCLKSYSSTOP_HSI    ) |
		REGISTER_FIELD_SETTER(RCC, CLKCFG, SYSCLKSYSSTOP, RCC_CLKCFG_SYSCLKSYSSTOP_HSI    ) |
		REGISTER_FIELD_SETTER(RCC, CLKCFG, SYSCLKSEL,     RCC_CLKCFG_SYSCLKSEL_HSI        ) )
	);

	// D1 clock configuration
	MODIFY_REG(RCC_COMMON->D1CLKCFG, (
		REGISTER_FIELD_SETTER(RCC, D1CLKCFG, COREPRE, RCC_D1CLKCFG_COREPRE_BYPASS ) |
		REGISTER_FIELD_SETTER(RCC, D1CLKCFG, APB3PRE, RCC_D1CLKCFG_APB3PRE_BYPASS ) |
		REGISTER_FIELD_SETTER(RCC, D1CLKCFG, AHBPRE,  RCC_D1CLKCFG_AHBPRE_BYPASS  ) )
	);

	// D2 clock configuration
	MODIFY_REG(RCC_COMMON->D2CLKCFG, (
		REGISTER_FIELD_SETTER(RCC, D2CLKCFG, APB2PRE, RCC_D2CLKCFG_APB2PRE_BYPASS ) |
		REGISTER_FIELD_SETTER(RCC, D2CLKCFG, APB1PRE, RCC_D2CLKCFG_APB1PRE_BYPASS ) )
	);

	// D3 clock configuration
	MODIFY_REG(RCC_COMMON->D3CLKCFG,
		REGISTER_FIELD_SETTER(RCC, D3CLKCFG, APB4PRE, RCC_D3CLKCFG_APB4PRE_BYPASS )
	);

	// PLL clock selection
	MODIFY_REG(RCC_COMMON->PLLCLKSEL, (
		REGISTER_FIELD_SETTER(RCC, PLLCLKSEL, PLL3PRE, RCC_PLLCLKSEL_PLL3PRE_DIV32 ) |
		REGISTER_FIELD_SETTER(RCC, PLLCLKSEL, PLL2PRE, RCC_PLLCLKSEL_PLL2PRE_DIV32 ) |
		REGISTER_FIELD_SETTER(RCC, PLLCLKSEL, PLL1PRE, RCC_PLLCLKSEL_PLL1PRE_DIV32 ) |
		REGISTER_FIELD_SETTER(RCC, PLLCLKSEL, PLLSRC,  RCC_PLLCLKSEL_PLLSRC_HSI    ) )
	);

	// PLL configuration
	MODIFY_REG(RCC_COMMON->PLLCFG, (
		REGISTER_FIELD_SETTER(RCC, PLLCFG, PLL3DIVR,      RCC_PLLCFG_PLL3DIVR_ENABLE     ) |
		REGISTER_FIELD_SETTER(RCC, PLLCFG, PLL3DIVQ,      RCC_PLLCFG_PLL3DIVQ_ENABLE     ) |
		REGISTER_FIELD_SETTER(RCC, PLLCFG, PLL3DIVP,      RCC_PLLCFG_PLL3DIVP_ENABLE     ) |
		REGISTER_FIELD_SETTER(RCC, PLLCFG, PLL2DIVR,      RCC_PLLCFG_PLL2DIVR_ENABLE     ) |
		REGISTER_FIELD_SETTER(RCC, PLLCFG, PLL2DIVQ,      RCC_PLLCFG_PLL2DIVQ_ENABLE     ) |
		REGISTER_FIELD_SETTER(RCC, PLLCFG, PLL2DIVP,      RCC_PLLCFG_PLL2DIVP_ENABLE     ) |
		REGISTER_FIELD_SETTER(RCC, PLLCFG, PLL1DIVR,      RCC_PLLCFG_PLL1DIVR_ENABLE     ) |
		REGISTER_FIELD_SETTER(RCC, PLLCFG, PLL1DIVQ,      RCC_PLLCFG_PLL1DIVQ_ENABLE     ) |
		REGISTER_FIELD_SETTER(RCC, PLLCFG, PLL1DIVP,      RCC_PLLCFG_PLL1DIVP_ENABLE     ) |
		REGISTER_FIELD_SETTER(RCC, PLLCFG, PLL3FREQRANGE, RCC_PLLCFG_PLLFREQRANGE_1_2MHZ ) |
		REGISTER_FIELD_SETTER(RCC, PLLCFG, PLL3VCOSEL,    RCC_PLLCFG_PLLVCOSEL_WIDE      ) |
		REGISTER_FIELD_SETTER(RCC, PLLCFG, PLL3FRAC,      RCC_PLLCFG_PLL3FRAC_DISABLE    ) |
		REGISTER_FIELD_SETTER(RCC, PLLCFG, PLL2FREQRANGE, RCC_PLLCFG_PLLFREQRANGE_1_2MHZ ) |
		REGISTER_FIELD_SETTER(RCC, PLLCFG, PLL2VCOSEL,    RCC_PLLCFG_PLLVCOSEL_WIDE      ) |
		REGISTER_FIELD_SETTER(RCC, PLLCFG, PLL2FRAC,      RCC_PLLCFG_PLL2FRAC_DISABLE    ) |
		REGISTER_FIELD_SETTER(RCC, PLLCFG, PLL1FREQRANGE, RCC_PLLCFG_PLLFREQRANGE_1_2MHZ ) |
		REGISTER_FIELD_SETTER(RCC, PLLCFG, PLL1VCOSEL,    RCC_PLLCFG_PLLVCOSEL_WIDE      ) |
		REGISTER_FIELD_SETTER(RCC, PLLCFG, PLL1FRAC,      RCC_PLLCFG_PLL1FRAC_DISABLE    ) )
	);

	// PLL1 divider configuration
	MODIFY_REG(RCC_COMMON->PLL1DIV, (
		REGISTER_FIELD_SETTER(RCC, PLLDIV, DIVR, RCC_PLLDIV_DIVR_DIV2   ) |
		REGISTER_FIELD_SETTER(RCC, PLLDIV, DIVQ, RCC_PLLDIV_DIVQ_DIV2   ) |
		REGISTER_FIELD_SETTER(RCC, PLLDIV, DIVP, RCC_PLLDIV_DIVP_DIV2   ) |
		REGISTER_FIELD_SETTER(RCC, PLLDIV, DIVN, RCC_PLLDIV_DIVN_DIV129 ) )
	);

	// PLL1 fractional divider configuration
	MODIFY_REG(RCC_COMMON->PLL1FRACDIV, (
		REGISTER_FIELD_SETTER(RCC, PLLFRACDIV, FRACN, 0x0UL ) )
	);

	// PLL2 divider configuration
	MODIFY_REG(RCC_COMMON->PLL2DIV, (
		REGISTER_FIELD_SETTER(RCC, PLLDIV, DIVR, RCC_PLLDIV_DIVR_DIV2   ) |
		REGISTER_FIELD_SETTER(RCC, PLLDIV, DIVQ, RCC_PLLDIV_DIVQ_DIV2   ) |
		REGISTER_FIELD_SETTER(RCC, PLLDIV, DIVP, RCC_PLLDIV_DIVP_DIV2   ) |
		REGISTER_FIELD_SETTER(RCC, PLLDIV, DIVN, RCC_PLLDIV_DIVN_DIV129 ) )
	);

	// PLL2 fractional divider configuration
	MODIFY_REG(RCC_COMMON->PLL2FRACDIV, (
		REGISTER_FIELD_SETTER(RCC, PLLFRACDIV, FRACN, 0x0UL ) )
	);

	// PLL3 divider configuration
	MODIFY_REG(RCC_COMMON->PLL3DIV, (
		REGISTER_FIELD_SETTER(RCC, PLLDIV, DIVR, RCC_PLLDIV_DIVR_DIV2   ) |
		REGISTER_FIELD_SETTER(RCC, PLLDIV, DIVQ, RCC_PLLDIV_DIVQ_DIV2   ) |
		REGISTER_FIELD_SETTER(RCC, PLLDIV, DIVP, RCC_PLLDIV_DIVP_DIV2   ) |
		REGISTER_FIELD_SETTER(RCC, PLLDIV, DIVN, RCC_PLLDIV_DIVN_DIV129 ) )
	);

	// PLL3 fractional divider configuration
	MODIFY_REG(RCC_COMMON->PLL3FRACDIV, (
		REGISTER_FIELD_SETTER(RCC, PLLFRACDIV, FRACN, 0x0UL ) )
	);

	// Disable interrupts
	MODIFY_REG(RCC_COMMON->CLKINTEN, (
		REGISTER_FIELD_SETTER(RCC, CLKINTEN, LSECLKSEC, RCC_CLKINTEN_LSECLKSEC_DISABLE ) |
		REGISTER_FIELD_SETTER(RCC, CLKINTEN, PLL3RDY,   RCC_CLKINTEN_PLL3RDY_DISABLE   ) |
		REGISTER_FIELD_SETTER(RCC, CLKINTEN, PLL2RDY,   RCC_CLKINTEN_PLL2RDY_DISABLE   ) |
		REGISTER_FIELD_SETTER(RCC, CLKINTEN, PLL1RDY,   RCC_CLKINTEN_PLL1RDY_DISABLE   ) |
		REGISTER_FIELD_SETTER(RCC, CLKINTEN, HSI48RDY,  RCC_CLKINTEN_HSI48RDY_DISABLE  ) |
		REGISTER_FIELD_SETTER(RCC, CLKINTEN, CSIRDY,    RCC_CLKINTEN_CSIRDY_DISABLE    ) |
		REGISTER_FIELD_SETTER(RCC, CLKINTEN, HSERDY,    RCC_CLKINTEN_HSERDY_DISABLE    ) |
		REGISTER_FIELD_SETTER(RCC, CLKINTEN, HSIRDY,    RCC_CLKINTEN_HSIRDY_DISABLE    ) |
		REGISTER_FIELD_SETTER(RCC, CLKINTEN, LSERDY,    RCC_CLKINTEN_LSERDY_DISABLE    ) |
		REGISTER_FIELD_SETTER(RCC, CLKINTEN, LSIRDY,    RCC_CLKINTEN_LSIRDY_DISABLE    ) )
	);

}
