/**
 * @copyright
 * @file boot.c
 * @author Andrea Gianarda
 * @date 26th of February 2021
 * @brief Boot functions
 */

#include "registers/peripheral/rcc.h"
#include "registers/peripheral/flash.h"

void systemInit(void) {

	// Reset value of flash read latency is 7, hence start the procedure to increase the clock frequency if too low
	if (GET_FIELD_VALUE(FLASH_BANK1->ACR, FLASH, ACR, LATENCY) < FLASH_LATENCY_7WAITSTATE) {
		MODIFY_FIELD(FLASH_BANK1->ACR, FLASH, ACR, LATENCY, FLASH_LATENCY_7WAITSTATE);
	}

	// Enable HSI only
	//MODIFY_REG(RCC_COMMON->CR, REGISTER_FIELD_SETTER(RCC, CR, HSION, RCC_CR_HSIEN_ENABLE))
	MODIFY_FIELD(RCC_COMMON->CR, RCC, CR, HSION, RCC_CLK_ENABLE);

	CLEAR_BITS(RCC_COMMON->CR, (
		REGISTER_FIELD_SETTER(RCC, CR, HSION,    RCC_CLK_DISABLE    ) |
		REGISTER_FIELD_SETTER(RCC, CR, HSIDIV,   RCC_HSIDIV_UPDATED ) |
		REGISTER_FIELD_SETTER(RCC, CR, CSION,    RCC_CLK_DISABLE    ) |
		REGISTER_FIELD_SETTER(RCC, CR, CSISMON,  RCC_CLK_DISABLE    ) |
		REGISTER_FIELD_SETTER(RCC, CR, HSI48ON,  RCC_CLK_DISABLE    ) |
		REGISTER_FIELD_SETTER(RCC, CR, HSEON,    RCC_CLK_DISABLE    ) |
		REGISTER_FIELD_SETTER(RCC, CR, HSEBYP,   RCC_HSE_NOBYPASS   ) |
		REGISTER_FIELD_SETTER(RCC, CR, HSECSSON, RCC_CLK_DISABLE    ) |
		REGISTER_FIELD_SETTER(RCC, CR, PLL1ON,   RCC_PLL_DISABLE    ) |
		REGISTER_FIELD_SETTER(RCC, CR, PLL2ON,   RCC_PLL_DISABLE    ) |
		REGISTER_FIELD_SETTER(RCC, CR, PLL3ON,   RCC_PLL_DISABLE    ) )
	);

	// Clock configuration
	MODIFY_REG(RCC_COMMON->CFGR, (
		REGISTER_FIELD_SETTER(RCC, CFGR, MCO2SEL,     RCC_MCO2_SYSCLK          ) |
		REGISTER_FIELD_SETTER(RCC, CFGR, MCO2PRE,     RCC_MCOPRE_DISABLE       ) |
		REGISTER_FIELD_SETTER(RCC, CFGR, MCO1SEL,     RCC_MCO1_HSI             ) |
		REGISTER_FIELD_SETTER(RCC, CFGR, MCO1PRE,     RCC_MCOPRE_DISABLE       ) |
		REGISTER_FIELD_SETTER(RCC, CFGR, TIMPRE,      RCC_TIMERPRE_MUL2        ) |
		REGISTER_FIELD_SETTER(RCC, CFGR, HRTIMSEL,    RCC_HRTIMERPRE_TIMERS    ) |
		REGISTER_FIELD_SETTER(RCC, CFGR, RTCPRE,      RCC_RTCPRE_NOCLK_DEFAULT ) |
		REGISTER_FIELD_SETTER(RCC, CFGR, STOPKERWUCK, RCC_KERCLKEXITSTOP_HSI   ) |
		REGISTER_FIELD_SETTER(RCC, CFGR, STOPWUCK,    RCC_SYSCLKEXITSTOP_HSI   ) |
		REGISTER_FIELD_SETTER(RCC, CFGR, SWS,         RCC_SYSCLK_HSI           ) )
	);

	// Reset value of flash read latency is 7, hence conclude the procedure to decrease the clock frequency if too high
	if (GET_FIELD_VALUE(FLASH_BANK1->ACR, FLASH, ACR, LATENCY) > FLASH_LATENCY_7WAITSTATE) {
		MODIFY_FIELD(FLASH_BANK1->ACR, FLASH, ACR, LATENCY, FLASH_LATENCY_7WAITSTATE);
	}

	// Set HSI clock trimming to 0x40
	MODIFY_FIELD(RCC_COMMON->HSICFGR, RCC, HSICFGR, HSITRIM, 0x40);

	// D1 clock configuration
	MODIFY_REG(RCC_COMMON->D1CFGR, (
		REGISTER_FIELD_SETTER(RCC, D1CFGR, D1CPRE, RCC_COREPRE_BYPASS ) |
		REGISTER_FIELD_SETTER(RCC, D1CFGR, D1PPRE, RCC_APBPRE_BYPASS  ) |
		REGISTER_FIELD_SETTER(RCC, D1CFGR, HPRE,   RCC_AHBPRE_BYPASS  ) )
	);

	// D2 clock configuration
	MODIFY_REG(RCC_COMMON->D2CFGR, (
		REGISTER_FIELD_SETTER(RCC, D2CFGR, D2PPRE2, RCC_APBPRE_BYPASS ) |
		REGISTER_FIELD_SETTER(RCC, D2CFGR, D2PPRE1, RCC_APBPRE_BYPASS ) )
	);

	// D3 clock configuration
	MODIFY_REG(RCC_COMMON->D3CFGR,
		REGISTER_FIELD_SETTER(RCC, D3CFGR, D3PPRE, RCC_APBPRE_BYPASS )
	);

	// PLL clock selection
	MODIFY_REG(RCC_COMMON->PLLCKSELR, (
		REGISTER_FIELD_SETTER(RCC, PLLCKSELR, DIVM3,  RCC_PLLPRE_DIV32 ) |
		REGISTER_FIELD_SETTER(RCC, PLLCKSELR, DIVM2,  RCC_PLLPRE_DIV32 ) |
		REGISTER_FIELD_SETTER(RCC, PLLCKSELR, DIVM1,  RCC_PLLPRE_DIV32 ) |
		REGISTER_FIELD_SETTER(RCC, PLLCKSELR, PLLSRC, RCC_PLLSRC_HSI   ) )
	);

	// PLL configuration
	MODIFY_REG(RCC_COMMON->PLLCFGR, (
		REGISTER_FIELD_SETTER(RCC, PLLCFGR, DIVR3EN,    RCC_PLLDIVR_ENABLE      ) |
		REGISTER_FIELD_SETTER(RCC, PLLCFGR, DIVQ3EN,    RCC_PLLDIVQ_ENABLE      ) |
		REGISTER_FIELD_SETTER(RCC, PLLCFGR, DIVP3EN,    RCC_PLLDIVP_ENABLE      ) |
		REGISTER_FIELD_SETTER(RCC, PLLCFGR, DIVR2EN,    RCC_PLLDIVR_ENABLE      ) |
		REGISTER_FIELD_SETTER(RCC, PLLCFGR, DIVQ2EN,    RCC_PLLDIVQ_ENABLE      ) |
		REGISTER_FIELD_SETTER(RCC, PLLCFGR, DIVP2EN,    RCC_PLLDIVP_ENABLE      ) |
		REGISTER_FIELD_SETTER(RCC, PLLCFGR, DIVR1EN,    RCC_PLLDIVR_ENABLE      ) |
		REGISTER_FIELD_SETTER(RCC, PLLCFGR, DIVQ1EN,    RCC_PLLDIVQ_ENABLE      ) |
		REGISTER_FIELD_SETTER(RCC, PLLCFGR, DIVP1EN,    RCC_PLLDIVP_ENABLE      ) |
		REGISTER_FIELD_SETTER(RCC, PLLCFGR, PLL3RGE,    RCC_PLLFREQRANGE_1_2MHZ ) |
		REGISTER_FIELD_SETTER(RCC, PLLCFGR, PLL3VCOSEL, RCC_PLLVCOSEL_WIDE      ) |
		REGISTER_FIELD_SETTER(RCC, PLLCFGR, PLL3FRACEN, RCC_PLLFRAC_DISABLE     ) |
		REGISTER_FIELD_SETTER(RCC, PLLCFGR, PLL2RGE,    RCC_PLLFREQRANGE_1_2MHZ ) |
		REGISTER_FIELD_SETTER(RCC, PLLCFGR, PLL2VCOSEL, RCC_PLLVCOSEL_WIDE      ) |
		REGISTER_FIELD_SETTER(RCC, PLLCFGR, PLL2FRACEN, RCC_PLLFRAC_DISABLE     ) |
		REGISTER_FIELD_SETTER(RCC, PLLCFGR, PLL1RGE,    RCC_PLLFREQRANGE_1_2MHZ ) |
		REGISTER_FIELD_SETTER(RCC, PLLCFGR, PLL1VCOSEL, RCC_PLLVCOSEL_WIDE      ) |
		REGISTER_FIELD_SETTER(RCC, PLLCFGR, PLL1FRACEN, RCC_PLLFRAC_DISABLE     ) )
	);

	// PLL1 divider configuration
	MODIFY_REG(RCC_COMMON->PLL1DIVR, (
		REGISTER_FIELD_SETTER(RCC, PLLDIVR, DIVR, RCC_PLLDIV2   ) |
		REGISTER_FIELD_SETTER(RCC, PLLDIVR, DIVQ, RCC_PLLDIV2   ) |
		REGISTER_FIELD_SETTER(RCC, PLLDIVR, DIVP, RCC_PLLDIV2   ) |
		REGISTER_FIELD_SETTER(RCC, PLLDIVR, DIVN, RCC_PLLDIV129 ) )
	);

	// PLL1 fractional divider configuration
	MODIFY_REG(RCC_COMMON->PLL1FRACR, (
		REGISTER_FIELD_SETTER(RCC, PLLFRACR, FRACN, 0x0UL ) )
	);

	// PLL2 divider configuration
	MODIFY_REG(RCC_COMMON->PLL2DIVR, (
		REGISTER_FIELD_SETTER(RCC, PLLDIVR, DIVR, RCC_PLLDIV2   ) |
		REGISTER_FIELD_SETTER(RCC, PLLDIVR, DIVQ, RCC_PLLDIV2   ) |
		REGISTER_FIELD_SETTER(RCC, PLLDIVR, DIVP, RCC_PLLDIV2   ) |
		REGISTER_FIELD_SETTER(RCC, PLLDIVR, DIVN, RCC_PLLDIV129 ) )
	);

	// PLL2 fractional divider configuration
	MODIFY_REG(RCC_COMMON->PLL2FRACR, (
		REGISTER_FIELD_SETTER(RCC, PLLFRACR, FRACN, 0x0UL ) )
	);

	// PLL3 divider configuration
	MODIFY_REG(RCC_COMMON->PLL3DIVR, (
		REGISTER_FIELD_SETTER(RCC, PLLDIVR, DIVR, RCC_PLLDIV2   ) |
		REGISTER_FIELD_SETTER(RCC, PLLDIVR, DIVQ, RCC_PLLDIV2   ) |
		REGISTER_FIELD_SETTER(RCC, PLLDIVR, DIVP, RCC_PLLDIV2   ) |
		REGISTER_FIELD_SETTER(RCC, PLLDIVR, DIVN, RCC_PLLDIV129 ) )
	);

	// PLL3 fractional divider configuration
	MODIFY_REG(RCC_COMMON->PLL3FRACR, (
		REGISTER_FIELD_SETTER(RCC, PLLFRACR, FRACN, 0x0UL ) )
	);

	// Disable interrupts
	MODIFY_REG(RCC_COMMON->CIER, (
		REGISTER_FIELD_SETTER(RCC, CIER, LSECSSIE,    RCC_CLKINT_DISABLE ) |
		REGISTER_FIELD_SETTER(RCC, CIER, PLL3RDYIE,   RCC_CLKINT_DISABLE ) |
		REGISTER_FIELD_SETTER(RCC, CIER, PLL2RDYIE,   RCC_CLKINT_DISABLE ) |
		REGISTER_FIELD_SETTER(RCC, CIER, PLL1RDYIE,   RCC_CLKINT_DISABLE ) |
		REGISTER_FIELD_SETTER(RCC, CIER, HSI48RDYIE,  RCC_CLKINT_DISABLE ) |
		REGISTER_FIELD_SETTER(RCC, CIER, CSIRDYIE,    RCC_CLKINT_DISABLE ) |
		REGISTER_FIELD_SETTER(RCC, CIER, HSERDYIE,    RCC_CLKINT_DISABLE ) |
		REGISTER_FIELD_SETTER(RCC, CIER, HSIRDYIE,    RCC_CLKINT_DISABLE ) |
		REGISTER_FIELD_SETTER(RCC, CIER, LSERDYIE,    RCC_CLKINT_DISABLE ) |
		REGISTER_FIELD_SETTER(RCC, CIER, LSIRDYIE,    RCC_CLKINT_DISABLE ) )
	);

}
