/**
 * @copyright
 * @file main.c
 * @author Andrea Gianarda
 * @date 17th of February 2021
 * @brief Main function
 */

#include "config/config.h"

#include "registers/gpio.h"
#include "registers/rcc.h"

void gpio_blink() {

	if (GET_FIELD_VALUE(GPIO_GPIOC->IDATA, GPIO, IDATA, PIN13) == GPIO_1) {
		if (GET_FIELD_VALUE(GPIO_GPIOB->ODATA, GPIO, ODATA, PIN0) == GPIO_0) {
			MODIFY_FIELD(GPIO_GPIOB->ODATA, GPIO, ODATA, PIN0, GPIO_1);
		} else if (GET_FIELD_VALUE(GPIO_GPIOE->ODATA, GPIO, ODATA, PIN1) == GPIO_0) {
			MODIFY_FIELD(GPIO_GPIOE->ODATA, GPIO, ODATA, PIN1, GPIO_1);
		} else if (GET_FIELD_VALUE(GPIO_GPIOB->ODATA, GPIO, ODATA, PIN14) == GPIO_0) {
			MODIFY_FIELD(GPIO_GPIOB->ODATA, GPIO, ODATA, PIN14, GPIO_1);
		} else if (GET_FIELD_VALUE(GPIO_GPIOB->ODATA, GPIO, ODATA, PIN0) == GPIO_1) {
			MODIFY_FIELD(GPIO_GPIOB->ODATA, GPIO, ODATA, PIN0, GPIO_0);
		} else if (GET_FIELD_VALUE(GPIO_GPIOE->ODATA, GPIO, ODATA, PIN1) == GPIO_1) {
			MODIFY_FIELD(GPIO_GPIOE->ODATA, GPIO, ODATA, PIN1, GPIO_0);
		} else if (GET_FIELD_VALUE(GPIO_GPIOB->ODATA, GPIO, ODATA, PIN14) == GPIO_1) {
			MODIFY_FIELD(GPIO_GPIOB->ODATA, GPIO, ODATA, PIN14, GPIO_0);
		}

		uint32_t counter = 0;
		while(counter < 100000) {
			counter++;
		}
	}
}

void gpio_setup() {

	MODIFY_FIELD(RCC_COMMON->AHB4CLKEN, RCC, AHB4CLKEN, GPIOB, RCC_PERIPHERALCLK_ENABLE);
	MODIFY_FIELD(RCC_COMMON->AHB4CLKEN, RCC, AHB4CLKEN, GPIOE, RCC_PERIPHERALCLK_ENABLE);


	// LED1 configuration is connected to PB0
	MODIFY_FIELD(GPIO_GPIOB->MODE, GPIO, MODE, PIN0, GPIO_MODE_OUTPUT);
	MODIFY_FIELD(GPIO_GPIOB->OTYPE, GPIO, OTYPE, PIN0, GPIO_OTYPE_PUSHPULL);
	MODIFY_FIELD(GPIO_GPIOB->OSPEED, GPIO, OTYPE, PIN0, GPIO_SPEED_HIGH);
	MODIFY_FIELD(GPIO_GPIOB->PUPD, GPIO, PUPD, PIN0, GPIO_NOPUPD);
	MODIFY_FIELD(GPIO_GPIOB->ODATA, GPIO, ODATA, PIN0, GPIO_0);

	// LED2 configuration is connected to PE1
	MODIFY_FIELD(GPIO_GPIOE->MODE, GPIO, MODE, PIN1, GPIO_MODE_OUTPUT);
	MODIFY_FIELD(GPIO_GPIOE->OTYPE, GPIO, OTYPE, PIN1, GPIO_OTYPE_PUSHPULL);
	MODIFY_FIELD(GPIO_GPIOE->OSPEED, GPIO, OTYPE, PIN1, GPIO_SPEED_MEDIUM);
	MODIFY_FIELD(GPIO_GPIOE->PUPD, GPIO, PUPD, PIN1, GPIO_NOPUPD);
	MODIFY_FIELD(GPIO_GPIOE->ODATA, GPIO, ODATA, PIN1, GPIO_1);

	// LED3 configuration is connected to PB14
	MODIFY_FIELD(GPIO_GPIOB->MODE, GPIO, MODE, PIN14, GPIO_MODE_OUTPUT);
	MODIFY_FIELD(GPIO_GPIOB->OTYPE, GPIO, OTYPE, PIN14, GPIO_OTYPE_PUSHPULL);
	MODIFY_FIELD(GPIO_GPIOB->OSPEED, GPIO, OTYPE, PIN14, GPIO_SPEED_LOW);
	MODIFY_FIELD(GPIO_GPIOB->PUPD, GPIO, PUPD, PIN14, GPIO_NOPUPD);
	MODIFY_FIELD(GPIO_GPIOB->ODATA, GPIO, ODATA, PIN14, GPIO_1);

	// User button is connected to PC13
	MODIFY_FIELD(GPIO_GPIOC->MODE, GPIO, MODE, PIN13, GPIO_MODE_INPUT);
	MODIFY_FIELD(GPIO_GPIOC->PUPD, GPIO, PUPD, PIN13, GPIO_PD);
}

int main(int argc, char * argv[]) {

	clk_config();

	gpio_setup();

	while(1) {
	//	gpio_blink();
	}

	return 0;

}
