/**
 * @copyright
 * @file main.c
 * @author Andrea Gianarda
 * @date 17th of February 2021
 * @brief Main function
 */

#include "config/config.h"

#include "registers/peripheral/gpio.h"
#include "registers/peripheral/rcc.h"

void gpio_blink() {

	if (GET_FIELD_VALUE(GPIO_GPIOC->IDR, GPIO, IDR, IDR13) == GPIO_1) {
		if (GET_FIELD_VALUE(GPIO_GPIOB->ODR, GPIO, ODR, ODR0) == GPIO_0) {
			MODIFY_FIELD(GPIO_GPIOB->ODR, GPIO, ODR, ODR0, GPIO_1);
		} else if (GET_FIELD_VALUE(GPIO_GPIOE->ODR, GPIO, ODR, ODR1) == GPIO_0) {
			MODIFY_FIELD(GPIO_GPIOE->ODR, GPIO, ODR, ODR1, GPIO_1);
		} else if (GET_FIELD_VALUE(GPIO_GPIOB->ODR, GPIO, ODR, ODR14) == GPIO_0) {
			MODIFY_FIELD(GPIO_GPIOB->ODR, GPIO, ODR, ODR14, GPIO_1);
		} else if (GET_FIELD_VALUE(GPIO_GPIOB->ODR, GPIO, ODR, ODR0) == GPIO_1) {
			MODIFY_FIELD(GPIO_GPIOB->ODR, GPIO, ODR, ODR0, GPIO_0);
		} else if (GET_FIELD_VALUE(GPIO_GPIOE->ODR, GPIO, ODR, ODR1) == GPIO_1) {
			MODIFY_FIELD(GPIO_GPIOE->ODR, GPIO, ODR, ODR1, GPIO_0);
		} else if (GET_FIELD_VALUE(GPIO_GPIOB->ODR, GPIO, ODR, ODR14) == GPIO_1) {
			MODIFY_FIELD(GPIO_GPIOB->ODR, GPIO, ODR, ODR14, GPIO_0);
		}

		uint32_t counter = 0;
		while(counter < 100000) {
			counter++;
		}
	}
}

void gpio_setup() {

	MODIFY_FIELD(RCC_COMMON->AHB4ENR, RCC, AHB4ENR, GPIOBEN, RCC_PERIPHERALCLK_ENABLE);
	MODIFY_FIELD(RCC_COMMON->AHB4ENR, RCC, AHB4ENR, GPIOEEN, RCC_PERIPHERALCLK_ENABLE);


	// LED1 configuration is connected to PB0
	MODIFY_FIELD(GPIO_GPIOB->MODER, GPIO, MODER, MODER0, GPIO_MODE_OUTPUT);
	MODIFY_FIELD(GPIO_GPIOB->OTYPER, GPIO, OTYPER, OT0, GPIO_OTYPE_PUSHPULL);
	MODIFY_FIELD(GPIO_GPIOB->OSPEEDR, GPIO, OSPEEDR, OSPEEDR0, GPIO_SPEED_HIGH);
	MODIFY_FIELD(GPIO_GPIOB->PUPDR, GPIO, PUPDR, PUPDR0, GPIO_NOPUPD);
	MODIFY_FIELD(GPIO_GPIOB->ODR, GPIO, ODR, ODR0, GPIO_0);

	// LED2 configuration is connected to PE1
	MODIFY_FIELD(GPIO_GPIOE->MODER, GPIO, MODER, MODER1, GPIO_MODE_OUTPUT);
	MODIFY_FIELD(GPIO_GPIOE->OTYPER, GPIO, OTYPER, OT1, GPIO_OTYPE_PUSHPULL);
	MODIFY_FIELD(GPIO_GPIOB->OSPEEDR, GPIO, OSPEEDR, OSPEEDR1, GPIO_SPEED_MEDIUM);
	MODIFY_FIELD(GPIO_GPIOE->PUPDR, GPIO, PUPDR, PUPDR1, GPIO_NOPUPD);
	MODIFY_FIELD(GPIO_GPIOE->ODR, GPIO, ODR, ODR1, GPIO_1);

	// LED3 configuration is connected to PB14
	MODIFY_FIELD(GPIO_GPIOB->MODER, GPIO, MODER, MODER14, GPIO_MODE_OUTPUT);
	MODIFY_FIELD(GPIO_GPIOB->OTYPER, GPIO, OTYPER, OT14, GPIO_OTYPE_PUSHPULL);
	MODIFY_FIELD(GPIO_GPIOB->OSPEEDR, GPIO, OSPEEDR, OSPEEDR14, GPIO_SPEED_LOW);
	MODIFY_FIELD(GPIO_GPIOB->PUPDR, GPIO, PUPDR, PUPDR14, GPIO_NOPUPD);
	MODIFY_FIELD(GPIO_GPIOB->ODR, GPIO, ODR, ODR14, GPIO_1);

	// User button is connected to PC13
	MODIFY_FIELD(GPIO_GPIOC->MODER, GPIO, MODER, MODER3, GPIO_MODE_INPUT);
	MODIFY_FIELD(GPIO_GPIOC->PUPDR, GPIO, PUPDR, PUPDR13, GPIO_PD);
}

int main(int argc, char * argv[]) {

	clk_config();

	gpio_setup();

	while(1) {
	//	gpio_blink();
	}

	return 0;

}
