#ifndef SCBFP_REGISTERS_H
#define SCBFP_REGISTERS_H
/**
 * @copyright
 * @file fp.h
 * @author Andrea Gianarda
 * @date 15th of April 2021
 * @brief Floating point (FP) extension of system control block (SCB) register
*/

#include <stdint.h>

/**
 *  @defgroup RegisterGroup Register global macros, structure and functions
 *  @brief Registers global macros, structure and functions
 *  @{
 */

/**
 *  @ingroup RegisterGroup
 *  @defgroup SCBFB Floating point (FP) extension of system control block (SCB) register
 *  @brief Floating point (FP) extension of system control block (SCB) registers macros and structures
 *  @{
 */

typedef struct {
	RW uint32_t FPCCR;   /*!< Floating point context control register         (Offset 0x00)  */
	RW uint32_t FPCAR;   /*!< Floating point context address register         (Offset 0x04)  */
	RW uint32_t FPDSCR;  /*!< Floating point default status control register  (Offset 0x08)  */
	RO uint32_t MVFR0;   /*!< Media and floating point feature 0 register     (Offset 0x0C)  */
	RO uint32_t MVFR1;   /*!< Media and floating point feature 1 register     (Offset 0x10)  */
	RO uint32_t MVFR2;   /*!< Media and floating point feature 2 register     (Offset 0x14)  */
} scs_scbfp_regs;

/*!< Floating point (FP) extension of system control block (SCB) registers */
/*!< Floating point context control register */
#define SCBFP_FPCCR_ADDRSTATEPRESEN_OFFSET   (31U)
#define SCBFP_FPCCR_ADDRSTATEPRESEN_MASK     (0x1UL << REGISTER_FIELD_OFFSET(SCBFP, FPCCR, ADDRSTATEPRESEN))   /*!< Mask  0x80000000 */

#define SCBFP_FPCCR_LAZYSTATEPRESEN_OFFSET   (30U)
#define SCBFP_FPCCR_LAZYSTATEPRESEN_MASK     (0x1UL << REGISTER_FIELD_OFFSET(SCBFP, FPCCR, LAZYSTATEPRESEN))   /*!< Mask  0x40000000 */

#define SCBFP_FPCCR_DBGMONRDY_OFFSET         (8U)
#define SCBFP_FPCCR_DBGMONRDY_MASK           (0x1UL << REGISTER_FIELD_OFFSET(SCBFP, FPCCR, DBGMONRDY))         /*!< Mask  0x00000100 */

#define SCBFP_FPCCR_BUSFAULTRDY_OFFSET       (6U)
#define SCBFP_FPCCR_BUSFAULTRDY_MASK         (0x1UL << REGISTER_FIELD_OFFSET(SCBFP, FPCCR, BUSFAULTRDY))       /*!< Mask  0x00000040 */

#define SCBFP_FPCCR_MEMMANAGERDY_OFFSET      (5U)
#define SCBFP_FPCCR_MEMMANAGERDY_MASK        (0x1UL << REGISTER_FIELD_OFFSET(SCBFP, FPCCR, MEMMANAGERDY))      /*!< Mask  0x00000020 */

#define SCBFP_FPCCR_HARDFAULTRDY_OFFSET      (4U)
#define SCBFP_FPCCR_HARDFAULTRDY_MASK        (0x1UL << REGISTER_FIELD_OFFSET(SCBFP, FPCCR, HARDFAULTRDY))      /*!< Mask  0x00000010 */

#define SCBFP_FPCCR_PROCMODE_OFFSET          (3U)
#define SCBFP_FPCCR_PROCMODE_MASK            (0x1UL << REGISTER_FIELD_OFFSET(SCBFP, FPCCR, PROCMODE))          /*!< Mask  0x00000008 */

#define SCBFP_FPCCR_PRIVILEGELEVEL_OFFSET    (1U)
#define SCBFP_FPCCR_PRIVILEGELEVEL_MASK      (0x1UL << REGISTER_FIELD_OFFSET(SCBFP, FPCCR, PRIVILEGELEVEL))    /*!< Mask  0x00000002 */

#define SCBFP_FPCCR_LAZYSTATEPRESACT_OFFSET  (0U)
#define SCBFP_FPCCR_LAZYSTATEPRESACT_MASK    (0x1UL << REGISTER_FIELD_OFFSET(SCBFP, FPCCR, LAZYSTATEPRESACT))  /*!< Mask  0x00000001 */

// Values of context address enable bit
#define SCBFP_ADDRSTATEPRES_DISABLE  (0x0UL)  /*!< Value 0x00000000 */
#define SCBFP_ADDRSTATEPRES_ENABLE   (0x1UL)  /*!< Value 0x00000001 */

// Values of automatic lazy context save enable bit
#define SCBFP_LAZYSTATEPRES_DISABLEAUTOMATICSAVE  (0x0UL)  /*!< Value 0x00000000 */
#define SCBFP_LAZYSTATEPRES_ENABLEAUTOMATICSAVE   (0x1UL)  /*!< Value 0x00000001 */

// Values of exception ready bit
#define SCBFP_EXCEPTIONRDY_NOTPENDING  (0x0UL)  /*!< Value 0x00000000 */
#define SCBFP_EXCEPTIONRDY_PENDING     (0x1UL)  /*!< Value 0x00000001 */

// Values of processor mode bit
#define SCBFP_PROCMODE_HANDLER  (0x0UL)  /*!< Value 0x00000000 */
#define SCBFP_PROCMODE_THREAD   (0x1UL)  /*!< Value 0x00000001 */

// Values of user privilege level bit
#define SCBFP_PRIVILEGELEVEL_PRIVILEGED    (0x0UL)  /*!< Value 0x00000000 */
#define SCBFP_PRIVILEGELEVEL_UNPRIVILEGED  (0x1UL)  /*!< Value 0x00000001 */

// Values of lazy state preservation active bit
#define SCBFP_PRIVILEGELEVEL_PRIVILEGED    (0x0UL)  /*!< Value 0x00000000 */
#define SCBFP_PRIVILEGELEVEL_UNPRIVILEGED  (0x1UL)  /*!< Value 0x00000001 */

// Values of lazy state preservation active bit
#define SCBFP_LAZYSTATEPRES_INACTIVE  (0x0UL)  /*!< Value 0x00000000 */
#define SCBFP_LAZYSTATEPRES_ACTIVE    (0x1UL)  /*!< Value 0x00000001 */

/*!< Floating point context address register */
#define SCBFP_FPCAR_ADDRSTATEPRESEN_OFFSET   (31U)
#define SCBFP_FPCAR_ADDRSTATEPRESEN_MASK     (0x1FFFFFFFUL << REGISTER_FIELD_OFFSET(SCBFP, FPCAR, ADDRSTATEPRESEN))   /*!< Mask  0xFFFFFFF8 */
#define SCBFP_FPCAR_ADDRSTATEPRESEN_0        (0x00000008UL << REGISTER_FIELD_OFFSET(SCBFP, FPCAR, ADDRSTATEPRESEN))   /*!< Mask  0x00000008 */
#define SCBFP_FPCAR_ADDRSTATEPRESEN_1        (0x00000010UL << REGISTER_FIELD_OFFSET(SCBFP, FPCAR, ADDRSTATEPRESEN))   /*!< Mask  0x00000010 */
#define SCBFP_FPCAR_ADDRSTATEPRESEN_2        (0x00000020UL << REGISTER_FIELD_OFFSET(SCBFP, FPCAR, ADDRSTATEPRESEN))   /*!< Mask  0x00000020 */
#define SCBFP_FPCAR_ADDRSTATEPRESEN_3        (0x00000040UL << REGISTER_FIELD_OFFSET(SCBFP, FPCAR, ADDRSTATEPRESEN))   /*!< Mask  0x00000040 */
#define SCBFP_FPCAR_ADDRSTATEPRESEN_4        (0x00000080UL << REGISTER_FIELD_OFFSET(SCBFP, FPCAR, ADDRSTATEPRESEN))   /*!< Mask  0x00000080 */
#define SCBFP_FPCAR_ADDRSTATEPRESEN_5        (0x00000100UL << REGISTER_FIELD_OFFSET(SCBFP, FPCAR, ADDRSTATEPRESEN))   /*!< Mask  0x00000100 */
#define SCBFP_FPCAR_ADDRSTATEPRESEN_6        (0x00000200UL << REGISTER_FIELD_OFFSET(SCBFP, FPCAR, ADDRSTATEPRESEN))   /*!< Mask  0x00000200 */
#define SCBFP_FPCAR_ADDRSTATEPRESEN_7        (0x00000400UL << REGISTER_FIELD_OFFSET(SCBFP, FPCAR, ADDRSTATEPRESEN))   /*!< Mask  0x00000400 */
#define SCBFP_FPCAR_ADDRSTATEPRESEN_8        (0x00000800UL << REGISTER_FIELD_OFFSET(SCBFP, FPCAR, ADDRSTATEPRESEN))   /*!< Mask  0x00000800 */
#define SCBFP_FPCAR_ADDRSTATEPRESEN_9        (0x00001000UL << REGISTER_FIELD_OFFSET(SCBFP, FPCAR, ADDRSTATEPRESEN))   /*!< Mask  0x00001000 */
#define SCBFP_FPCAR_ADDRSTATEPRESEN_10       (0x00002000UL << REGISTER_FIELD_OFFSET(SCBFP, FPCAR, ADDRSTATEPRESEN))   /*!< Mask  0x00002000 */
#define SCBFP_FPCAR_ADDRSTATEPRESEN_11       (0x00004000UL << REGISTER_FIELD_OFFSET(SCBFP, FPCAR, ADDRSTATEPRESEN))   /*!< Mask  0x00004000 */
#define SCBFP_FPCAR_ADDRSTATEPRESEN_12       (0x00008000UL << REGISTER_FIELD_OFFSET(SCBFP, FPCAR, ADDRSTATEPRESEN))   /*!< Mask  0x00008000 */
#define SCBFP_FPCAR_ADDRSTATEPRESEN_13       (0x00010000UL << REGISTER_FIELD_OFFSET(SCBFP, FPCAR, ADDRSTATEPRESEN))   /*!< Mask  0x00010000 */
#define SCBFP_FPCAR_ADDRSTATEPRESEN_14       (0x00020000UL << REGISTER_FIELD_OFFSET(SCBFP, FPCAR, ADDRSTATEPRESEN))   /*!< Mask  0x00020000 */
#define SCBFP_FPCAR_ADDRSTATEPRESEN_15       (0x00040000UL << REGISTER_FIELD_OFFSET(SCBFP, FPCAR, ADDRSTATEPRESEN))   /*!< Mask  0x00040000 */
#define SCBFP_FPCAR_ADDRSTATEPRESEN_16       (0x00080000UL << REGISTER_FIELD_OFFSET(SCBFP, FPCAR, ADDRSTATEPRESEN))   /*!< Mask  0x00080000 */
#define SCBFP_FPCAR_ADDRSTATEPRESEN_17       (0x00100000UL << REGISTER_FIELD_OFFSET(SCBFP, FPCAR, ADDRSTATEPRESEN))   /*!< Mask  0x00100000 */
#define SCBFP_FPCAR_ADDRSTATEPRESEN_18       (0x00200000UL << REGISTER_FIELD_OFFSET(SCBFP, FPCAR, ADDRSTATEPRESEN))   /*!< Mask  0x00200000 */
#define SCBFP_FPCAR_ADDRSTATEPRESEN_19       (0x00400000UL << REGISTER_FIELD_OFFSET(SCBFP, FPCAR, ADDRSTATEPRESEN))   /*!< Mask  0x00400000 */
#define SCBFP_FPCAR_ADDRSTATEPRESEN_20       (0x00800000UL << REGISTER_FIELD_OFFSET(SCBFP, FPCAR, ADDRSTATEPRESEN))   /*!< Mask  0x00800000 */
#define SCBFP_FPCAR_ADDRSTATEPRESEN_21       (0x01000000UL << REGISTER_FIELD_OFFSET(SCBFP, FPCAR, ADDRSTATEPRESEN))   /*!< Mask  0x01000000 */
#define SCBFP_FPCAR_ADDRSTATEPRESEN_22       (0x02000000UL << REGISTER_FIELD_OFFSET(SCBFP, FPCAR, ADDRSTATEPRESEN))   /*!< Mask  0x02000000 */
#define SCBFP_FPCAR_ADDRSTATEPRESEN_23       (0x04000000UL << REGISTER_FIELD_OFFSET(SCBFP, FPCAR, ADDRSTATEPRESEN))   /*!< Mask  0x04000000 */
#define SCBFP_FPCAR_ADDRSTATEPRESEN_24       (0x08000000UL << REGISTER_FIELD_OFFSET(SCBFP, FPCAR, ADDRSTATEPRESEN))   /*!< Mask  0x08000000 */
#define SCBFP_FPCAR_ADDRSTATEPRESEN_25       (0x10000000UL << REGISTER_FIELD_OFFSET(SCBFP, FPCAR, ADDRSTATEPRESEN))   /*!< Mask  0x10000000 */
#define SCBFP_FPCAR_ADDRSTATEPRESEN_26       (0x20000000UL << REGISTER_FIELD_OFFSET(SCBFP, FPCAR, ADDRSTATEPRESEN))   /*!< Mask  0x20000000 */
#define SCBFP_FPCAR_ADDRSTATEPRESEN_27       (0x40000000UL << REGISTER_FIELD_OFFSET(SCBFP, FPCAR, ADDRSTATEPRESEN))   /*!< Mask  0x40000000 */
#define SCBFP_FPCAR_ADDRSTATEPRESEN_28       (0x80000000UL << REGISTER_FIELD_OFFSET(SCBFP, FPCAR, ADDRSTATEPRESEN))   /*!< Mask  0x80000000 */

#define SYSCTRL_OFFSET 0x0
#define SYSCTRL_BASE (SCS_BASE + SYSCTRL_OFFSET)
#define SYSCTRL REGISTER_PTR(scs_sysctrl_regs, SYSCTRL_BASE)

/** @} */ // End of SysCtrl group

/** @} */ // End of RegisterGroup group

#endif // SCBFP_REGISTERS_H
