#ifndef SCBFP_REGISTERS_H
#define SCBFP_REGISTERS_H
/**
 * @copyright
 * @file fp.h
 * @author Andrea Gianarda
 * @date 15th of April 2021
 * @brief Floating point (FP) extension of system control block (SCB) register
*/

#include <stdint.h>

/**
 *  @defgroup RegisterGroup Register global macros, structure and functions
 *  @brief Registers global macros, structure and functions
 *  @{
 */

/**
 *  @ingroup RegisterGroup
 *  @defgroup SCBFB Floating point (FP) extension of system control block (SCB) register
 *  @brief Floating point (FP) extension of system control block (SCB) registers macros and structures
 *  @{
 */

typedef struct {
	RW uint32_t FPCCR;   /*!< Floating point context control register         (Offset 0x00)  */
	RW uint32_t FPCAR;   /*!< Floating point context address register         (Offset 0x04)  */
	RW uint32_t FPDSCR;  /*!< Floating point default status control register  (Offset 0x08)  */
	RO uint32_t MVFR0;   /*!< Media and floating point feature 0 register     (Offset 0x0C)  */
	RO uint32_t MVFR1;   /*!< Media and floating point feature 1 register     (Offset 0x10)  */
	RO uint32_t MVFR2;   /*!< Media and floating point feature 2 register     (Offset 0x14)  */
} scs_scbfp_regs;

/*!< Floating point (FP) extension of system control block (SCB) registers */
/*!< Floating point context control register */
#define SCBFP_FPCCR_ADDRSTATEPRESEN_OFFSET   (31U)
#define SCBFP_FPCCR_ADDRSTATEPRESEN_MASK     (0x1UL << REGISTER_FIELD_OFFSET(SCBFP, FPCCR, ADDRSTATEPRESEN))   /*!< Mask  0x80000000 */

#define SCBFP_FPCCR_LAZYSTATEPRESEN_OFFSET   (30U)
#define SCBFP_FPCCR_LAZYSTATEPRESEN_MASK     (0x1UL << REGISTER_FIELD_OFFSET(SCBFP, FPCCR, LAZYSTATEPRESEN))   /*!< Mask  0x40000000 */

#define SCBFP_FPCCR_DBGMONRDY_OFFSET         (8U)
#define SCBFP_FPCCR_DBGMONRDY_MASK           (0x1UL << REGISTER_FIELD_OFFSET(SCBFP, FPCCR, DBGMONRDY))         /*!< Mask  0x00000100 */

#define SCBFP_FPCCR_BUSFAULTRDY_OFFSET       (6U)
#define SCBFP_FPCCR_BUSFAULTRDY_MASK         (0x1UL << REGISTER_FIELD_OFFSET(SCBFP, FPCCR, BUSFAULTRDY))       /*!< Mask  0x00000040 */

#define SCBFP_FPCCR_MEMMANAGERDY_OFFSET      (5U)
#define SCBFP_FPCCR_MEMMANAGERDY_MASK        (0x1UL << REGISTER_FIELD_OFFSET(SCBFP, FPCCR, MEMMANAGERDY))      /*!< Mask  0x00000020 */

#define SCBFP_FPCCR_HARDFAULTRDY_OFFSET      (4U)
#define SCBFP_FPCCR_HARDFAULTRDY_MASK        (0x1UL << REGISTER_FIELD_OFFSET(SCBFP, FPCCR, HARDFAULTRDY))      /*!< Mask  0x00000010 */

#define SCBFP_FPCCR_PROCMODE_OFFSET          (3U)
#define SCBFP_FPCCR_PROCMODE_MASK            (0x1UL << REGISTER_FIELD_OFFSET(SCBFP, FPCCR, PROCMODE))          /*!< Mask  0x00000008 */

#define SCBFP_FPCCR_PRIVILEGELEVEL_OFFSET    (1U)
#define SCBFP_FPCCR_PRIVILEGELEVEL_MASK      (0x1UL << REGISTER_FIELD_OFFSET(SCBFP, FPCCR, PRIVILEGELEVEL))    /*!< Mask  0x00000002 */

#define SCBFP_FPCCR_LAZYSTATEPRESACT_OFFSET  (0U)
#define SCBFP_FPCCR_LAZYSTATEPRESACT_MASK    (0x1UL << REGISTER_FIELD_OFFSET(SCBFP, FPCCR, LAZYSTATEPRESACT))  /*!< Mask  0x00000001 */

// Values of context address enable bit
#define SCBFP_ADDRSTATEPRES_DISABLE  (0x0UL)  /*!< Value 0x00000000 */
#define SCBFP_ADDRSTATEPRES_ENABLE   (0x1UL)  /*!< Value 0x00000001 */

// Values of automatic lazy context save enable bit
#define SCBFP_LAZYSTATEPRES_DISABLEAUTOMATICSAVE  (0x0UL)  /*!< Value 0x00000000 */
#define SCBFP_LAZYSTATEPRES_ENABLEAUTOMATICSAVE   (0x1UL)  /*!< Value 0x00000001 */

// Values of exception ready bit
#define SCBFP_EXCEPTIONRDY_NOTPENDING  (0x0UL)  /*!< Value 0x00000000 */
#define SCBFP_EXCEPTIONRDY_PENDING     (0x1UL)  /*!< Value 0x00000001 */

// Values of processor mode bit
#define SCBFP_PROCMODE_HANDLER  (0x0UL)  /*!< Value 0x00000000 */
#define SCBFP_PROCMODE_THREAD   (0x1UL)  /*!< Value 0x00000001 */

// Values of user privilege level bit
#define SCBFP_PRIVILEGELEVEL_PRIVILEGED    (0x0UL)  /*!< Value 0x00000000 */
#define SCBFP_PRIVILEGELEVEL_UNPRIVILEGED  (0x1UL)  /*!< Value 0x00000001 */

// Values of lazy state preservation active bit
#define SCBFP_PRIVILEGELEVEL_PRIVILEGED    (0x0UL)  /*!< Value 0x00000000 */
#define SCBFP_PRIVILEGELEVEL_UNPRIVILEGED  (0x1UL)  /*!< Value 0x00000001 */

// Values of lazy state preservation active bit
#define SCBFP_LAZYSTATEPRES_INACTIVE  (0x0UL)  /*!< Value 0x00000000 */
#define SCBFP_LAZYSTATEPRES_ACTIVE    (0x1UL)  /*!< Value 0x00000001 */

/*!< Floating point context address register */
#define SCBFP_FPCAR_ADDRESS_OFFSET   (3U)
#define SCBFP_FPCAR_ADDRESS_MASK     (0x1FFFFFFFUL << REGISTER_FIELD_OFFSET(SCBFP, FPCAR, ADDRESS))   /*!< Mask  0xFFFFFFF8 */
#define SCBFP_FPCAR_ADDRESS_0        (0x00000008UL << REGISTER_FIELD_OFFSET(SCBFP, FPCAR, ADDRESS))   /*!< Mask  0x00000008 */
#define SCBFP_FPCAR_ADDRESS_1        (0x00000010UL << REGISTER_FIELD_OFFSET(SCBFP, FPCAR, ADDRESS))   /*!< Mask  0x00000010 */
#define SCBFP_FPCAR_ADDRESS_2        (0x00000020UL << REGISTER_FIELD_OFFSET(SCBFP, FPCAR, ADDRESS))   /*!< Mask  0x00000020 */
#define SCBFP_FPCAR_ADDRESS_3        (0x00000040UL << REGISTER_FIELD_OFFSET(SCBFP, FPCAR, ADDRESS))   /*!< Mask  0x00000040 */
#define SCBFP_FPCAR_ADDRESS_4        (0x00000080UL << REGISTER_FIELD_OFFSET(SCBFP, FPCAR, ADDRESS))   /*!< Mask  0x00000080 */
#define SCBFP_FPCAR_ADDRESS_5        (0x00000100UL << REGISTER_FIELD_OFFSET(SCBFP, FPCAR, ADDRESS))   /*!< Mask  0x00000100 */
#define SCBFP_FPCAR_ADDRESS_6        (0x00000200UL << REGISTER_FIELD_OFFSET(SCBFP, FPCAR, ADDRESS))   /*!< Mask  0x00000200 */
#define SCBFP_FPCAR_ADDRESS_7        (0x00000400UL << REGISTER_FIELD_OFFSET(SCBFP, FPCAR, ADDRESS))   /*!< Mask  0x00000400 */
#define SCBFP_FPCAR_ADDRESS_8        (0x00000800UL << REGISTER_FIELD_OFFSET(SCBFP, FPCAR, ADDRESS))   /*!< Mask  0x00000800 */
#define SCBFP_FPCAR_ADDRESS_9        (0x00001000UL << REGISTER_FIELD_OFFSET(SCBFP, FPCAR, ADDRESS))   /*!< Mask  0x00001000 */
#define SCBFP_FPCAR_ADDRESS_10       (0x00002000UL << REGISTER_FIELD_OFFSET(SCBFP, FPCAR, ADDRESS))   /*!< Mask  0x00002000 */
#define SCBFP_FPCAR_ADDRESS_11       (0x00004000UL << REGISTER_FIELD_OFFSET(SCBFP, FPCAR, ADDRESS))   /*!< Mask  0x00004000 */
#define SCBFP_FPCAR_ADDRESS_12       (0x00008000UL << REGISTER_FIELD_OFFSET(SCBFP, FPCAR, ADDRESS))   /*!< Mask  0x00008000 */
#define SCBFP_FPCAR_ADDRESS_13       (0x00010000UL << REGISTER_FIELD_OFFSET(SCBFP, FPCAR, ADDRESS))   /*!< Mask  0x00010000 */
#define SCBFP_FPCAR_ADDRESS_14       (0x00020000UL << REGISTER_FIELD_OFFSET(SCBFP, FPCAR, ADDRESS))   /*!< Mask  0x00020000 */
#define SCBFP_FPCAR_ADDRESS_15       (0x00040000UL << REGISTER_FIELD_OFFSET(SCBFP, FPCAR, ADDRESS))   /*!< Mask  0x00040000 */
#define SCBFP_FPCAR_ADDRESS_16       (0x00080000UL << REGISTER_FIELD_OFFSET(SCBFP, FPCAR, ADDRESS))   /*!< Mask  0x00080000 */
#define SCBFP_FPCAR_ADDRESS_17       (0x00100000UL << REGISTER_FIELD_OFFSET(SCBFP, FPCAR, ADDRESS))   /*!< Mask  0x00100000 */
#define SCBFP_FPCAR_ADDRESS_18       (0x00200000UL << REGISTER_FIELD_OFFSET(SCBFP, FPCAR, ADDRESS))   /*!< Mask  0x00200000 */
#define SCBFP_FPCAR_ADDRESS_19       (0x00400000UL << REGISTER_FIELD_OFFSET(SCBFP, FPCAR, ADDRESS))   /*!< Mask  0x00400000 */
#define SCBFP_FPCAR_ADDRESS_20       (0x00800000UL << REGISTER_FIELD_OFFSET(SCBFP, FPCAR, ADDRESS))   /*!< Mask  0x00800000 */
#define SCBFP_FPCAR_ADDRESS_21       (0x01000000UL << REGISTER_FIELD_OFFSET(SCBFP, FPCAR, ADDRESS))   /*!< Mask  0x01000000 */
#define SCBFP_FPCAR_ADDRESS_22       (0x02000000UL << REGISTER_FIELD_OFFSET(SCBFP, FPCAR, ADDRESS))   /*!< Mask  0x02000000 */
#define SCBFP_FPCAR_ADDRESS_23       (0x04000000UL << REGISTER_FIELD_OFFSET(SCBFP, FPCAR, ADDRESS))   /*!< Mask  0x04000000 */
#define SCBFP_FPCAR_ADDRESS_24       (0x08000000UL << REGISTER_FIELD_OFFSET(SCBFP, FPCAR, ADDRESS))   /*!< Mask  0x08000000 */
#define SCBFP_FPCAR_ADDRESS_25       (0x10000000UL << REGISTER_FIELD_OFFSET(SCBFP, FPCAR, ADDRESS))   /*!< Mask  0x10000000 */
#define SCBFP_FPCAR_ADDRESS_26       (0x20000000UL << REGISTER_FIELD_OFFSET(SCBFP, FPCAR, ADDRESS))   /*!< Mask  0x20000000 */
#define SCBFP_FPCAR_ADDRESS_27       (0x40000000UL << REGISTER_FIELD_OFFSET(SCBFP, FPCAR, ADDRESS))   /*!< Mask  0x40000000 */
#define SCBFP_FPCAR_ADDRESS_28       (0x80000000UL << REGISTER_FIELD_OFFSET(SCBFP, FPCAR, ADDRESS))   /*!< Mask  0x80000000 */

/*!< Floating point default status control register */
#define SCBFP_FPDSCR_ALTHALFPRECISIONFORMAT_OFFSET  (26U)
#define SCBFP_FPDSCR_ALTHALFPRECISIONFORMAT_MASK    (0x1UL << REGISTER_FIELD_OFFSET(SCBFP, FPDSCR, ALTHALFPRECISIONFORMAT))  /*!< Mask  0x04000000 */

#define SCBFP_FPDSCR_DEFAULTNAN_OFFSET              (25U)
#define SCBFP_FPDSCR_DEFAULTNAN_MASK                (0x1UL << REGISTER_FIELD_OFFSET(SCBFP, FPDSCR, DEFAULTNAN))              /*!< Mask  0x02000000 */

#define SCBFP_FPDSCR_FLUSHTOZERO_OFFSET             (24U)
#define SCBFP_FPDSCR_FLUSHTOZERO_MASK               (0x1UL << REGISTER_FIELD_OFFSET(SCBFP, FPDSCR, FLUSHTOZERO))             /*!< Mask  0x01000000 */

#define SCBFP_FPDSCR_ROUNDINGMODE_OFFSET            (22U)
#define SCBFP_FPDSCR_ROUNDINGMODE_MASK              (0x3UL << REGISTER_FIELD_OFFSET(SCBFP, FPDSCR, ROUNDINGMODE))            /*!< Mask  0x00C00000 */

/*!< Media and floating point feature 0 register */
#define SCBFP_MVFR0_ROUNDINGMODES_OFFSET      (28U)
#define SCBFP_MVFR0_ROUNDINGMODES_MASK        (0xFUL << REGISTER_FIELD_OFFSET(SCBFP, MVFR0, ROUNDINGMODES))      /*!< Mask  0xF0000000 */
#define SCBFP_MVFR0_ROUNDINGMODES_0           (0x1UL << REGISTER_FIELD_OFFSET(SCBFP, MVFR0, ROUNDINGMODES))      /*!< Value 0x10000000 */
#define SCBFP_MVFR0_ROUNDINGMODES_1           (0x2UL << REGISTER_FIELD_OFFSET(SCBFP, MVFR0, ROUNDINGMODES))      /*!< Value 0x20000000 */
#define SCBFP_MVFR0_ROUNDINGMODES_2           (0x4UL << REGISTER_FIELD_OFFSET(SCBFP, MVFR0, ROUNDINGMODES))      /*!< Value 0x40000000 */
#define SCBFP_MVFR0_ROUNDINGMODES_3           (0x8UL << REGISTER_FIELD_OFFSET(SCBFP, MVFR0, ROUNDINGMODES))      /*!< Value 0x80000000 */

#define SCBFP_MVFR0_SHORTVECTOR_OFFSET        (24U)
#define SCBFP_MVFR0_SHORTVECTOR_MASK          (0xFUL << REGISTER_FIELD_OFFSET(SCBFP, MVFR0, SHORTVECTOR))        /*!< Mask  0x0F000000 */
#define SCBFP_MVFR0_SHORTVECTOR_0             (0x1UL << REGISTER_FIELD_OFFSET(SCBFP, MVFR0, SHORTVECTOR))        /*!< Value 0x01000000 */
#define SCBFP_MVFR0_SHORTVECTOR_1             (0x2UL << REGISTER_FIELD_OFFSET(SCBFP, MVFR0, SHORTVECTOR))        /*!< Value 0x02000000 */
#define SCBFP_MVFR0_SHORTVECTOR_2             (0x4UL << REGISTER_FIELD_OFFSET(SCBFP, MVFR0, SHORTVECTOR))        /*!< Value 0x04000000 */
#define SCBFP_MVFR0_SHORTVECTOR_3             (0x8UL << REGISTER_FIELD_OFFSET(SCBFP, MVFR0, SHORTVECTOR))        /*!< Value 0x08000000 */

#define SCBFP_MVFR0_SQUAREROOT_OFFSET         (20U)
#define SCBFP_MVFR0_SQUAREROOT_MASK           (0xFUL << REGISTER_FIELD_OFFSET(SCBFP, MVFR0, SQUAREROOT))         /*!< Mask  0x00F00000 */
#define SCBFP_MVFR0_SQUAREROOT_0              (0x1UL << REGISTER_FIELD_OFFSET(SCBFP, MVFR0, SQUAREROOT))         /*!< Value 0x00100000 */
#define SCBFP_MVFR0_SQUAREROOT_1              (0x2UL << REGISTER_FIELD_OFFSET(SCBFP, MVFR0, SQUAREROOT))         /*!< Value 0x00200000 */
#define SCBFP_MVFR0_SQUAREROOT_2              (0x4UL << REGISTER_FIELD_OFFSET(SCBFP, MVFR0, SQUAREROOT))         /*!< Value 0x00400000 */
#define SCBFP_MVFR0_SQUAREROOT_3              (0x8UL << REGISTER_FIELD_OFFSET(SCBFP, MVFR0, SQUAREROOT))         /*!< Value 0x00800000 */

#define SCBFP_MVFR0_DIVIDE_OFFSET             (16U)
#define SCBFP_MVFR0_DIVIDE_MASK               (0xFUL << REGISTER_FIELD_OFFSET(SCBFP, MVFR0, DIVIDE))             /*!< Mask  0x000F0000 */
#define SCBFP_MVFR0_DIVIDE_0                  (0x1UL << REGISTER_FIELD_OFFSET(SCBFP, MVFR0, DIVIDE))             /*!< Value 0x00010000 */
#define SCBFP_MVFR0_DIVIDE_1                  (0x2UL << REGISTER_FIELD_OFFSET(SCBFP, MVFR0, DIVIDE))             /*!< Value 0x00020000 */
#define SCBFP_MVFR0_DIVIDE_2                  (0x4UL << REGISTER_FIELD_OFFSET(SCBFP, MVFR0, DIVIDE))             /*!< Value 0x00040000 */
#define SCBFP_MVFR0_DIVIDE_3                  (0x8UL << REGISTER_FIELD_OFFSET(SCBFP, MVFR0, DIVIDE))             /*!< Value 0x00080000 */

#define SCBFP_MVFR0_EXCEPTIONTRAPPING_OFFSET  (12U)
#define SCBFP_MVFR0_EXCEPTIONTRAPPING_MASK    (0xFUL << REGISTER_FIELD_OFFSET(SCBFP, MVFR0, EXCEPTIONTRAPPING))  /*!< Mask  0x0000F000 */
#define SCBFP_MVFR0_EXCEPTIONTRAPPING_0       (0x1UL << REGISTER_FIELD_OFFSET(SCBFP, MVFR0, EXCEPTIONTRAPPING))  /*!< Value 0x00001000 */
#define SCBFP_MVFR0_EXCEPTIONTRAPPING_1       (0x2UL << REGISTER_FIELD_OFFSET(SCBFP, MVFR0, EXCEPTIONTRAPPING))  /*!< Value 0x00002000 */
#define SCBFP_MVFR0_EXCEPTIONTRAPPING_2       (0x4UL << REGISTER_FIELD_OFFSET(SCBFP, MVFR0, EXCEPTIONTRAPPING))  /*!< Value 0x00004000 */
#define SCBFP_MVFR0_EXCEPTIONTRAPPING_3       (0x8UL << REGISTER_FIELD_OFFSET(SCBFP, MVFR0, EXCEPTIONTRAPPING))  /*!< Value 0x00008000 */

#define SCBFP_MVFR0_DOUBLEPRECISION_OFFSET    (8U)
#define SCBFP_MVFR0_DOUBLEPRECISION_MASK      (0xFUL << REGISTER_FIELD_OFFSET(SCBFP, MVFR0, DOUBLEPRECISION))    /*!< Mask  0x00000F00 */
#define SCBFP_MVFR0_DOUBLEPRECISION_0         (0x1UL << REGISTER_FIELD_OFFSET(SCBFP, MVFR0, DOUBLEPRECISION))    /*!< Value 0x00000100 */
#define SCBFP_MVFR0_DOUBLEPRECISION_1         (0x2UL << REGISTER_FIELD_OFFSET(SCBFP, MVFR0, DOUBLEPRECISION))    /*!< Value 0x00000200 */
#define SCBFP_MVFR0_DOUBLEPRECISION_2         (0x4UL << REGISTER_FIELD_OFFSET(SCBFP, MVFR0, DOUBLEPRECISION))    /*!< Value 0x00000400 */
#define SCBFP_MVFR0_DOUBLEPRECISION_3         (0x8UL << REGISTER_FIELD_OFFSET(SCBFP, MVFR0, DOUBLEPRECISION))    /*!< Value 0x00000800 */

#define SCBFP_MVFR0_SINGLEPRECISION_OFFSET    (4U)
#define SCBFP_MVFR0_SINGLEPRECISION_MASK      (0xFUL << REGISTER_FIELD_OFFSET(SCBFP, MVFR0, SINGLEPRECISION))    /*!< Mask  0x000000F0 */
#define SCBFP_MVFR0_SINGLEPRECISION_0         (0x1UL << REGISTER_FIELD_OFFSET(SCBFP, MVFR0, SINGLEPRECISION))    /*!< Value 0x00000010 */
#define SCBFP_MVFR0_SINGLEPRECISION_1         (0x2UL << REGISTER_FIELD_OFFSET(SCBFP, MVFR0, SINGLEPRECISION))    /*!< Value 0x00000020 */
#define SCBFP_MVFR0_SINGLEPRECISION_2         (0x4UL << REGISTER_FIELD_OFFSET(SCBFP, MVFR0, SINGLEPRECISION))    /*!< Value 0x00000040 */
#define SCBFP_MVFR0_SINGLEPRECISION_3         (0x8UL << REGISTER_FIELD_OFFSET(SCBFP, MVFR0, SINGLEPRECISION))    /*!< Value 0x00000080 */

#define SCBFP_MVFR0_REGISTERBANKSIZE_OFFSET   (0U)
#define SCBFP_MVFR0_REGISTERBANKSIZE_MASK     (0xFUL << REGISTER_FIELD_OFFSET(SCBFP, MVFR0, REGISTERBANKSIZE))   /*!< Mask  0x0000000F */
#define SCBFP_MVFR0_REGISTERBANKSIZE_0        (0x1UL << REGISTER_FIELD_OFFSET(SCBFP, MVFR0, REGISTERBANKSIZE))   /*!< Value 0x00000001 */
#define SCBFP_MVFR0_REGISTERBANKSIZE_1        (0x2UL << REGISTER_FIELD_OFFSET(SCBFP, MVFR0, REGISTERBANKSIZE))   /*!< Value 0x00000002 */
#define SCBFP_MVFR0_REGISTERBANKSIZE_2        (0x4UL << REGISTER_FIELD_OFFSET(SCBFP, MVFR0, REGISTERBANKSIZE))   /*!< Value 0x00000004 */
#define SCBFP_MVFR0_REGISTERBANKSIZE_3        (0x8UL << REGISTER_FIELD_OFFSET(SCBFP, MVFR0, REGISTERBANKSIZE))   /*!< Value 0x00000008 */

// Values of rounding modes support register
#define SCBFP_ROUNDINGMODES_ALLSUPPORTED  (0x1UL)  /*!< Value 0x00000001 */

// Values of short vectors support register
#define SCBFP_SHORTVECTOR_NOTSUPPORTED  (0x0UL)  /*!< Value 0x00000000 */

// Values of square root support register
#define SCBFP_SQUAREROOT_SUPPORTED  (0x1UL)  /*!< Value 0x00000001 */

// Values of divide support register
#define SCBFP_DIVIDE_SUPPORTED  (0x1UL)  /*!< Value 0x00000001 */

// Values of exception trapping support register
#define SCBFP_EXCEPTIONTRAPPING_NOTSUPPORTED  (0x0UL)  /*!< Value 0x00000000 */
#define SCBFP_EXCEPTIONTRAPPING_SUPPORTED     (0x2UL)  /*!< Value 0x00000002 */

// Values of double precision support register
#define SCBFP_DOUBLEPRECISION_SUPPORTED     (0x2UL)  /*!< Value 0x00000002 */

// Values of single precision support register
#define SCBFP_SINGLEPRECISION_SUPPORTED     (0x2UL)  /*!< Value 0x00000002 */

// Values of register bank size register
#define SCBFP_REGISTERBANK_16REGS  (0x1UL)  /*!< Value 0x00000001 */

/*!< Media and floating point feature 1 register */
#define SCBFP_MVFR1_FUSEDMAC_OFFSET             (28U)
#define SCBFP_MVFR1_FUSEDMAC_MASK               (0xFUL << REGISTER_FIELD_OFFSET(SCBFP, MVFR1, FUSEDMAC))      /*!< Mask  0xF0000000 */
#define SCBFP_MVFR1_FUSEDMAC_0                  (0x1UL << REGISTER_FIELD_OFFSET(SCBFP, MVFR1, FUSEDMAC))      /*!< Value 0x10000000 */
#define SCBFP_MVFR1_FUSEDMAC_1                  (0x2UL << REGISTER_FIELD_OFFSET(SCBFP, MVFR1, FUSEDMAC))      /*!< Value 0x20000000 */
#define SCBFP_MVFR1_FUSEDMAC_2                  (0x4UL << REGISTER_FIELD_OFFSET(SCBFP, MVFR1, FUSEDMAC))      /*!< Value 0x40000000 */
#define SCBFP_MVFR1_FUSEDMAC_3                  (0x8UL << REGISTER_FIELD_OFFSET(SCBFP, MVFR1, FUSEDMAC))      /*!< Value 0x80000000 */

#define SCBFP_MVFR1_HALFPRECDBLPRECCONV_OFFSET  (24U)
#define SCBFP_MVFR1_HALFPRECDBLPRECCONV_MASK    (0xFUL << REGISTER_FIELD_OFFSET(SCBFP, MVFR1, HALFPRECDBLPRECCONV))        /*!< Mask  0x0F000000 */
#define SCBFP_MVFR1_HALFPRECDBLPRECCONV_0       (0x1UL << REGISTER_FIELD_OFFSET(SCBFP, MVFR1, HALFPRECDBLPRECCONV))        /*!< Value 0x01000000 */
#define SCBFP_MVFR1_HALFPRECDBLPRECCONV_1       (0x2UL << REGISTER_FIELD_OFFSET(SCBFP, MVFR1, HALFPRECDBLPRECCONV))        /*!< Value 0x02000000 */
#define SCBFP_MVFR1_HALFPRECDBLPRECCONV_2       (0x4UL << REGISTER_FIELD_OFFSET(SCBFP, MVFR1, HALFPRECDBLPRECCONV))        /*!< Value 0x04000000 */
#define SCBFP_MVFR1_HALFPRECDBLPRECCONV_3       (0x8UL << REGISTER_FIELD_OFFSET(SCBFP, MVFR1, HALFPRECDBLPRECCONV))        /*!< Value 0x08000000 */

#define SCBFP_MVFR1_NANMODE_OFFSET              (4U)
#define SCBFP_MVFR1_NANMODE_MASK                (0xFUL << REGISTER_FIELD_OFFSET(SCBFP, MVFR1, NANMODE))    /*!< Mask  0x000000F0 */
#define SCBFP_MVFR1_NANMODE_0                   (0x1UL << REGISTER_FIELD_OFFSET(SCBFP, MVFR1, NANMODE))    /*!< Value 0x00000010 */
#define SCBFP_MVFR1_NANMODE_1                   (0x2UL << REGISTER_FIELD_OFFSET(SCBFP, MVFR1, NANMODE))    /*!< Value 0x00000020 */
#define SCBFP_MVFR1_NANMODE_2                   (0x4UL << REGISTER_FIELD_OFFSET(SCBFP, MVFR1, NANMODE))    /*!< Value 0x00000040 */
#define SCBFP_MVFR1_NANMODE_3                   (0x8UL << REGISTER_FIELD_OFFSET(SCBFP, MVFR1, NANMODE))    /*!< Value 0x00000080 */

#define SCBFP_MVFR1_FLUSHTOZEROMODE_OFFSET      (0U)
#define SCBFP_MVFR1_FLUSHTOZEROMODE_MASK        (0xFUL << REGISTER_FIELD_OFFSET(SCBFP, MVFR1, FLUSHTOZEROMODE))   /*!< Mask  0x0000000F */
#define SCBFP_MVFR1_FLUSHTOZEROMODE_0           (0x1UL << REGISTER_FIELD_OFFSET(SCBFP, MVFR1, FLUSHTOZEROMODE))   /*!< Value 0x00000001 */
#define SCBFP_MVFR1_FLUSHTOZEROMODE_1           (0x2UL << REGISTER_FIELD_OFFSET(SCBFP, MVFR1, FLUSHTOZEROMODE))   /*!< Value 0x00000002 */
#define SCBFP_MVFR1_FLUSHTOZEROMODE_2           (0x4UL << REGISTER_FIELD_OFFSET(SCBFP, MVFR1, FLUSHTOZEROMODE))   /*!< Value 0x00000004 */
#define SCBFP_MVFR1_FLUSHTOZEROMODE_3           (0x8UL << REGISTER_FIELD_OFFSET(SCBFP, MVFR1, FLUSHTOZEROMODE))   /*!< Value 0x00000008 */

// Values of fused MAC support register
#define SCBFP_FUSEDMAC_SUPPORTED  (0x1UL)  /*!< Value 0x00000001 */

// Values of half precision to double precision conversion support register
#define SCBFP_HALFPRECDBLPRECCONV_HALFTOSGL           (0x1UL)  /*!< Value 0x00000001 */
#define SCBFP_HALFPRECDBLPRECCONV_DBLTOHALFHALFTOSGL  (0x2UL)  /*!< Value 0x00000002 */

// Values of NaN mode register
#define SCBFP_NANMODE_PROPAGATION  (0x1UL)  /*!< Value 0x00000001 */

// Values of flush to zero mode register
#define SCBFP_FLUSHTOZEROMODE_FULLDENORMALIZEDARITHMETICS  (0x1UL)  /*!< Value 0x00000001 */

/*!< Media and floating point feature 2 register */
#define SCBFP_MVFR2_MISCFEATURES_OFFSET  (4U)
#define SCBFP_MVFR2_MISCFEATURES_MASK    (0xFUL << REGISTER_FIELD_OFFSET(SCBFP, MVFR2, MISCFEATURES))    /*!< Mask  0x000000F0 */
#define SCBFP_MVFR2_MISCFEATURES_0       (0x1UL << REGISTER_FIELD_OFFSET(SCBFP, MVFR2, MISCFEATURES))    /*!< Value 0x00000010 */
#define SCBFP_MVFR2_MISCFEATURES_1       (0x2UL << REGISTER_FIELD_OFFSET(SCBFP, MVFR2, MISCFEATURES))    /*!< Value 0x00000020 */
#define SCBFP_MVFR2_MISCFEATURES_2       (0x4UL << REGISTER_FIELD_OFFSET(SCBFP, MVFR2, MISCFEATURES))    /*!< Value 0x00000040 */
#define SCBFP_MVFR2_MISCFEATURES_3       (0x8UL << REGISTER_FIELD_OFFSET(SCBFP, MVFR2, MISCFEATURES))    /*!< Value 0x00000080 */

// Values of floating point miscellaneous feature support register
#define SCBFP_MISCFEATURES_NONE                (0x0UL)  /*!< Value 0x00000000 */
#define SCBFP_MISCFEATURES_FPSELINTCONVMAXMIN  (0x4UL)  /*!< Value 0x00000004 */

#define SYSCTRL_OFFSET 0x0
#define SYSCTRL_BASE (SCS_BASE + SYSCTRL_OFFSET)
#define SYSCTRL REGISTER_PTR(scs_sysctrl_regs, SYSCTRL_BASE)

/** @} */ // End of SysCtrl group

/** @} */ // End of RegisterGroup group

#endif // SCBFP_REGISTERS_H
