#ifndef SYSCTRL_REGISTERS_H
#define SYSCTRL_REGISTERS_H
/**
 * @copyright
 * @file sysctrl.h
 * @author Andrea Gianarda
 * @date 30th of March 2021
 * @brief System control registers in system control space (SCS) register
*/

#include <stdint.h>

/**
 *  @defgroup RegisterGroup Register global macros, structure and functions
 *  @brief Registers global macros, structure and functions
 *  @{
 */

/**
 *  @ingroup RegisterGroup
 *  @defgroup SysCtrl System control registers in system control space (SCS)
 *  @brief System control registers in system control space (SCS) macros and structures
 *  @{
 */

typedef struct {
	   uint32_t reserved0;  /*!< Reserved                             (Offset 0x0) */
	RO uint32_t ICTR;        /*!< Interrupt controller type register  (Offset 0x4) */
	RW uint32_t ACTLR;       /*!< Auxiliary control register          (Offset 0x8) */
	   uint32_t reserved1;  /*!< Reserved                             (Offset 0xC) */
} scs_sysctrl_regs;

/*!< System control registers in system control space (SCS) registers */
/*!< Interrupt controller type register */
#define SYSCTRL_ICTR_INTLINESNUM_OFFSET  (0U)
#define SYSCTRL_ICTR_INTLINESNUM_MASK    (0xFUL << REGISTER_FIELD_OFFSET(SYSCTRL, ICTR, INTLINESNUM))  /*!< Mask  0x0000000F */

// Available delays between non volatile memory signals during programming operations
#define SYSCTRL_INTLINES_0_31     (0x0UL)  /*!< Value 0x00000000 */
#define SYSCTRL_INTLINES_32_63    (0x1UL)  /*!< Value 0x00000001 */
#define SYSCTRL_INTLINES_64_95    (0x2UL)  /*!< Value 0x00000002 */
#define SYSCTRL_INTLINES_96_127   (0x3UL)  /*!< Value 0x00000003 */
#define SYSCTRL_INTLINES_128_159  (0x4UL)  /*!< Value 0x00000004 */
#define SYSCTRL_INTLINES_160_191  (0x5UL)  /*!< Value 0x00000005 */
#define SYSCTRL_INTLINES_192_223  (0x6UL)  /*!< Value 0x00000006 */
#define SYSCTRL_INTLINES_224_256  (0x7UL)  /*!< Value 0x00000007 */
#define SYSCTRL_INTLINES_256_287  (0x8UL)  /*!< Value 0x00000008 */
#define SYSCTRL_INTLINES_288_319  (0x9UL)  /*!< Value 0x00000009 */
#define SYSCTRL_INTLINES_320_351  (0xAUL)  /*!< Value 0x0000000A */
#define SYSCTRL_INTLINES_352_383  (0xBUL)  /*!< Value 0x0000000B */
#define SYSCTRL_INTLINES_384_415  (0xCUL)  /*!< Value 0x0000000C */
#define SYSCTRL_INTLINES_416_447  (0xDUL)  /*!< Value 0x0000000D */
#define SYSCTRL_INTLINES_448_479  (0xEUL)  /*!< Value 0x0000000E */
#define SYSCTRL_INTLINES_480_495  (0xFUL)  /*!< Value 0x0000000F */

/*!< Auxiliary control register */
#define SYSCTRL_ACTLR_DISFPUISSOPT_OFFSET    (28U)
#define SYSCTRL_ACTLR_DISFPUISSOPT_MASK      (0x1UL << REGISTER_FIELD_OFFSET(SYSCTRL, ACTLR, DISFPUISSOPT))    /*!< Mask  0x10000000 */

#define SYSCTRL_ACTLR_DISCRITAXIRUW_OFFSET   (27U)
#define SYSCTRL_ACTLR_DISCRITAXIRUW_MASK     (0x1UL << REGISTER_FIELD_OFFSET(SYSCTRL, ACTLR, DISCRITAXIRUW))   /*!< Mask  0x08000000 */

#define SYSCTRL_ACTLR_DISDYNALL_OFFSET       (26U)
#define SYSCTRL_ACTLR_DISDYNALL_MASK         (0x1UL << REGISTER_FIELD_OFFSET(SYSCTRL, ACTLR, DISDYNALL))       /*!< Mask  0x04000000 */

#define SYSCTRL_ACTLR_DISISSCH1_OFFSET       (21U)
#define SYSCTRL_ACTLR_DISISSCH1_MASK         (0xFUL << REGISTER_FIELD_OFFSET(SYSCTRL, ACTLR, DISISSCH1))       /*!< Mask  0x03E00000 */

#define SYSCTRL_ACTLR_DISDI_OFFSET           (16U)
#define SYSCTRL_ACTLR_DISDI_MASK             (0xFUL << REGISTER_FIELD_OFFSET(SYSCTRL, ACTLR, DISDI))           /*!< Mask  0x001F0000 */

#define SYSCTRL_ACTLR_DISCRITAXIRUR_OFFSET   (15U)
#define SYSCTRL_ACTLR_DISCRITAXIRUR_MASK     (0x1UL << REGISTER_FIELD_OFFSET(SYSCTRL, ACTLR, DISCRITAXIRUR))   /*!< Mask  0x00008000 */

#define SYSCTRL_ACTLR_DISBTACALLOC_OFFSET    (14U)
#define SYSCTRL_ACTLR_DISBTACALLOC_MASK      (0x1UL << REGISTER_FIELD_OFFSET(SYSCTRL, ACTLR, DISBTACALLOC))    /*!< Mask  0x00004000 */

#define SYSCTRL_ACTLR_DISBTACREAD_OFFSET     (13U)
#define SYSCTRL_ACTLR_DISBTACREAD_MASK       (0x1UL << REGISTER_FIELD_OFFSET(SYSCTRL, ACTLR, DISBTACREAD))     /*!< Mask  0x00002000 */

#define SYSCTRL_ACTLR_DISITMATBFLUSH_OFFSET  (12U)
#define SYSCTRL_ACTLR_DISITMATBFLUSH_MASK    (0x1UL << REGISTER_FIELD_OFFSET(SYSCTRL, ACTLR, DISITMATBFLUSH))  /*!< Mask  0x00001000 */

#define SYSCTRL_ACTLR_DISRAMODE_OFFSET       (11U)
#define SYSCTRL_ACTLR_DISRAMODE_MASK         (0x1UL << REGISTER_FIELD_OFFSET(SYSCTRL, ACTLR, DISRAMODE))       /*!< Mask  0x00000800 */

#define SYSCTRL_ACTLR_FPUEXCODIS_OFFSET      (10U)
#define SYSCTRL_ACTLR_FPUEXCODIS_MASK        (0x1UL << REGISTER_FIELD_OFFSET(SYSCTRL, ACTLR, FPUEXCODIS))      /*!< Mask  0x00000400 */

#define SYSCTRL_ACTLR_DISFOLD_OFFSET         (2U)
#define SYSCTRL_ACTLR_DISFOLD_MASK           (0x1UL << REGISTER_FIELD_OFFSET(SYSCTRL, ACTLR, DISFOLD))         /*!< Mask  0x00000004 */

// Values of dual issue bits
#define SYSCTRL_DUALISSUE_VFP              (4U)
#define SYSCTRL_DUALISSUE_INTMACMUL        (3U)
#define SYSCTRL_DUALISSUE_LOADPC           (2U)
#define SYSCTRL_DUALISSUE_INDIRECTBRANCH   (1U)
#define SYSCTRL_DUALISSUE_DIRECTBRANCH     (0U)

// Values of dual issue in channel 1 register bits
#define SYSCTRL_DUALISSUECH1_VPF_OFFSET             (REGISTER_FIELD_OFFSET(SYSCTRL, ACTLR, DISDI) + SYSCTRL_DUALISSUE_VFP)
#define SYSCTRL_DUALISSUECH1_VPF_MASK               (0x1UL << REGISTER_FIELD_OFFSET(SYSCTRL, DUALISSUECH1, VPF))             /*!< Mask  0x02000000 */

#define SYSCTRL_DUALISSUECH1_INTMACMUL_OFFSET       (REGISTER_FIELD_OFFSET(SYSCTRL, ACTLR, DISDI) + SYSCTRL_DUALISSUE_INTMACMUL)
#define SYSCTRL_DUALISSUECH1_INTMACMUL_MASK         (0x1UL << REGISTER_FIELD_OFFSET(SYSCTRL, DUALISSUECH1, INTMACMUL))       /*!< Mask  0x01000000 */

#define SYSCTRL_DUALISSUECH1_LOADPC_OFFSET          (REGISTER_FIELD_OFFSET(SYSCTRL, ACTLR, DISDI) + SYSCTRL_DUALISSUE_LOADPC)
#define SYSCTRL_DUALISSUECH1_LOADPC_MASK            (0x1UL << REGISTER_FIELD_OFFSET(SYSCTRL, DUALISSUECH1, LOADPC))          /*!< Mask  0x00800000 */

#define SYSCTRL_DUALISSUECH1_INDIRECTBRANCH_OFFSET  (REGISTER_FIELD_OFFSET(SYSCTRL, ACTLR, DISDI) + SYSCTRL_DUALISSUE_INDIRECTBRANCH)
#define SYSCTRL_DUALISSUECH1_INDIRECTBRANCH_MASK    (0x1UL << REGISTER_FIELD_OFFSET(SYSCTRL, DUALISSUECH1, INDIRECTBRANCH))  /*!< Mask  0x00400000 */

#define SYSCTRL_DUALISSUECH1_DIRECTBRANCH_OFFSET    (REGISTER_FIELD_OFFSET(SYSCTRL, ACTLR, DISDI) + SYSCTRL_DUALISSUE_DIRECTBRANCH)
#define SYSCTRL_DUALISSUECH1_DIRECTBRANCH_MASK      (0x1UL << REGISTER_FIELD_OFFSET(SYSCTRL, DUALISSUECH1, DIRECTBRANCH))    /*!< Mask  0x00200000 */

// Values of dual issue in channel 0 register bits
#define SYSCTRL_DUALISSUECH0_VPF_OFFSET             (REGISTER_FIELD_OFFSET(SYSCTRL, ACTLR, DISDI) + SYSCTRL_DUALISSUE_VFP)
#define SYSCTRL_DUALISSUECH0_VPF_MASK               (0x1UL << REGISTER_FIELD_OFFSET(SYSCTRL, DUALISSUECH0, VPF))             /*!< Mask  0x00100000 */

#define SYSCTRL_DUALISSUECH0_INTMACMUL_OFFSET       (REGISTER_FIELD_OFFSET(SYSCTRL, ACTLR, DISDI) + SYSCTRL_DUALISSUE_INTMACMUL)
#define SYSCTRL_DUALISSUECH0_INTMACMUL_MASK         (0x1UL << REGISTER_FIELD_OFFSET(SYSCTRL, DUALISSUECH0, INTMACMUL))       /*!< Mask  0x00080000 */

#define SYSCTRL_DUALISSUECH0_LOADPC_OFFSET          (REGISTER_FIELD_OFFSET(SYSCTRL, ACTLR, DISDI) + SYSCTRL_DUALISSUE_LOADPC)
#define SYSCTRL_DUALISSUECH0_LOADPC_MASK            (0x1UL << REGISTER_FIELD_OFFSET(SYSCTRL, DUALISSUECH0, LOADPC))          /*!< Mask  0x00040000 */

#define SYSCTRL_DUALISSUECH0_INDIRECTBRANCH_OFFSET  (REGISTER_FIELD_OFFSET(SYSCTRL, ACTLR, DISDI) + SYSCTRL_DUALISSUE_INDIRECTBRANCH)
#define SYSCTRL_DUALISSUECH0_INDIRECTBRANCH_MASK    (0x1UL << REGISTER_FIELD_OFFSET(SYSCTRL, DUALISSUECH0, INDIRECTBRANCH))  /*!< Mask  0x00020000 */

#define SYSCTRL_DUALISSUECH0_DIRECTBRANCH_OFFSET    (REGISTER_FIELD_OFFSET(SYSCTRL, ACTLR, DISDI) + SYSCTRL_DUALISSUE_DIRECTBRANCH)
#define SYSCTRL_DUALISSUECH0_DIRECTBRANCH_MASK      (0x1UL << REGISTER_FIELD_OFFSET(SYSCTRL, DUALISSUECH0, DIRECTBRANCH))    /*!< Mask  0x00010000 */

// Values of enable bits
#define SYSCTRL_ENABLE   (0x0UL)  /*!< Value 0x00000000 */
#define SYSCTRL_DISABLE  (0x1UL)  /*!< Value 0x00000001 */

#define SYSCTRL_OFFSET 0x0UL
#define SYSCTRL_BASE OFFSET_ADDRESS(SCS_BASE, SYSCTRL_OFFSET)
#define SYSCTRL REGISTER_PTR(scs_sysctrl_regs, SYSCTRL_BASE)

/** @} */ // End of SysCtrl group

/** @} */ // End of RegisterGroup group

#endif // SYSCTRL_REGISTERS_H
